(()=>{"use strict";const O=window.CinemapOcean,c=document.getElementById("ocean"),ctx=c.getContext("2d",{alpha:false});let movies=[],eco,cam={x:0,y:0,targetX:0,targetY:0},t0=performance.now(),drag=null;
function safeArray(v){return Array.isArray(v)?v:[]}function readLocal(){let out=[];for(const key of ["cinemap.ocean.movies","cinemap-my-list","cinemap-my-saved-list"]){try{const v=JSON.parse(localStorage.getItem(key)||"null"),a=Array.isArray(v)?v:(v&&Array.isArray(v.picks)?v.picks:[]);out.push(...a)}catch{}}const seen=new Set;return out.filter(m=>{if(!m||!m.title)return false;const k=String(m.tmdbId||m.id||m.title);if(seen.has(k))return false;seen.add(k);return true})}
async function enrich(input){try{const r=await fetch("data/movies.json",{cache:"force-cache"}),all=await r.json(),list=Array.isArray(all)?all:(all.movies||[]),byId=new Map(list.map(m=>[String(m.tmdbId||m.id),m])),byTitle=new Map(list.map(m=>[String(m.title||"").toLowerCase(),m]));return input.map(m=>({...byTitle.get(String(m.title).toLowerCase()),...byId.get(String(m.tmdbId||m.id)),...m}))}catch{return input}}
function resize(){const d=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;c.width=Math.round(w*d);c.height=Math.round(h*d);c.style.width=w+"px";c.style.height=h+"px";ctx.setTransform(d,0,0,d,0,0)}
function rnd(seed,n=1){return(O.hash(seed)%10000)/10000*n}function pos(p,i){const s=String(p.movie.id||p.movie.title),band=p.habitat==="twilight"?.68:p.habitat==="reef"?.58:p.habitat==="open-ocean"?.38:.5;return{x:(rnd(s+"x",1.8)-.4)*innerWidth+cam.x,y:(band*.72+rnd(s+"y",.32))*innerHeight+cam.y,z:.55+rnd(s+"z",.9)}}
function fish(x,y,s,h,tail=1){ctx.fillStyle=`hsla(${h},72%,68%,.88)`;ctx.beginPath();ctx.ellipse(x,y,s*1.7,s*.78,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(x-s*1.5,y);ctx.lineTo(x-s*(2.2+tail*.4),y-s*.9);ctx.lineTo(x-s*(2.2+tail*.4),y+s*.9);ctx.closePath();ctx.fill();ctx.fillStyle="#07171aaa";ctx.beginPath();ctx.arc(x+s*.85,y-s*.14,Math.max(1,s*.1),0,7);ctx.fill()}
function drawCreature(p,i,time){const q=pos(p,i),s=(5+p.variant.scale*6)*q.z,bob=Math.sin(time*.0012+i)*5*q.z,h=p.variant.hue,x=q.x,y=q.y+bob,id=p.species.id;ctx.save();ctx.globalAlpha=Math.min(1,.45+q.z*.45);
if(id==="jelly"){ctx.fillStyle=`hsla(${h},65%,78%,.48)`;ctx.beginPath();ctx.arc(x,y,s*1.15,Math.PI,0);ctx.quadraticCurveTo(x,y+s*.8,x-s*1.15,y);ctx.fill();ctx.strokeStyle=`hsla(${h},70%,82%,.4)`;for(let k=-2;k<=2;k++){ctx.beginPath();ctx.moveTo(x+k*s*.35,y);ctx.quadraticCurveTo(x+k*s*.5,y+s*1.7,x+k*s*.25,y+s*2.8);ctx.stroke()}}
else if(["ray","manta"].includes(id)){ctx.fillStyle=`hsla(${h},55%,65%,.82)`;ctx.beginPath();ctx.moveTo(x-s*2.4,y);ctx.quadraticCurveTo(x,y-s*1.2,x+s*2.4,y);ctx.quadraticCurveTo(x,y+s*1.3,x-s*2.4,y);ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.beginPath();ctx.moveTo(x-s*1.5,y);ctx.lineTo(x-s*4,y+s*.25);ctx.stroke()}
else if(id==="turtle"){ctx.fillStyle=`hsla(${h},45%,55%,.9)`;ctx.beginPath();ctx.ellipse(x,y,s*1.35,s,0,0,7);ctx.fill();for(const a of [-.65,.65]){ctx.beginPath();ctx.ellipse(x+a*s,y+s*.75,s*.75,s*.25,a,0,7);ctx.fill()}ctx.beginPath();ctx.arc(x+s*1.55,y,s*.32,0,7);ctx.fill()}
else if(id==="octopus"){ctx.fillStyle=`hsla(${h},65%,62%,.86)`;ctx.beginPath();ctx.arc(x,y-s*.3,s,Math.PI,0);ctx.lineTo(x+s,y+s*.5);ctx.lineTo(x-s,y+s*.5);ctx.fill();ctx.strokeStyle=ctx.fillStyle;ctx.lineWidth=s*.18;for(let k=-3;k<=3;k++){ctx.beginPath();ctx.moveTo(x+k*s*.24,y+s*.35);ctx.quadraticCurveTo(x+k*s*.5+Math.sin(time*.002+k)*s,y+s*1.8,x+k*s*.7,y+s*2.4);ctx.stroke()}}
else if(id==="shark"){ctx.fillStyle=`hsla(${h},20%,60%,.9)`;ctx.beginPath();ctx.moveTo(x+s*2.5,y);ctx.quadraticCurveTo(x,y-s,x-s*2.1,y);ctx.quadraticCurveTo(x,y+s,x+s*2.5,y);ctx.fill();ctx.beginPath();ctx.moveTo(x-s*2,y);ctx.lineTo(x-s*3,y-s*1.2);ctx.lineTo(x-s*2.8,y+s*1.2);ctx.fill();ctx.beginPath();ctx.moveTo(x,y-s*.75);ctx.lineTo(x-s*.4,y-s*1.8);ctx.lineTo(x+s*.6,y-s*.65);ctx.fill()}
else if(id==="whale"){fish(x,y,s*2,h,.6);ctx.fillStyle=`hsla(${h},30%,65%,.8)`;ctx.beginPath();ctx.moveTo(x-s,y+s);ctx.quadraticCurveTo(x,y+s*2,x+s*.7,y+s*.6);ctx.fill()}
else if(id==="seahorse"){ctx.strokeStyle=`hsla(${h},70%,65%,.9)`;ctx.lineWidth=s*.55;ctx.beginPath();ctx.arc(x,y,s*.7,-1.4,1.6);ctx.quadraticCurveTo(x-s,y+s*1.6,x,y+s*2);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x+s*.55,y-s*.5);ctx.lineTo(x+s*1.2,y-s*.7);ctx.lineTo(x+s*.55,y-s*.1);ctx.fill()}
else fish(x,y,s,h,id==="moonfish"?.35:1);ctx.restore()}
function background(time){const w=innerWidth,h=innerHeight,g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#167081");g.addColorStop(.18,"#0b5363");g.addColorStop(.58,"#062b39");g.addColorStop(1,"#020b11");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.save();ctx.globalCompositeOperation="screen";for(let i=0;i<8;i++){ctx.fillStyle="rgba(105,225,220,.018)";ctx.beginPath();ctx.moveTo(w*(i/7)-80,0);ctx.lineTo(w*(i/7)+150,h*.7);ctx.lineTo(w*(i/7)+250,h*.7);ctx.lineTo(w*(i/7)+40,0);ctx.fill()}ctx.restore();ctx.fillStyle="#041217";ctx.beginPath();ctx.moveTo(0,h*.88);for(let x=0;x<=w;x+=40)ctx.lineTo(x,h*.86+rnd("floor"+x,.08)*h);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();const plants=Math.min(55,8+(eco?.environment.seaweed||0));for(let i=0;i<plants;i++){const px=rnd("plant"+i,w),ph=25+rnd("ph"+i,100);ctx.strokeStyle="rgba(37,111,91,.48)";ctx.lineWidth=1.5+rnd("pw"+i,2);ctx.beginPath();ctx.moveTo(px,h);ctx.quadraticCurveTo(px+Math.sin(time*.001+i)*15,h-ph*.5,px-5,h-ph);ctx.stroke()}for(let i=0;i<Math.min(90,(eco?.environment.richness||0)*90+12);i++){const bx=rnd("bubblex"+i,w),speed=8+rnd("bs"+i,25),by=h-((time*.01*speed+rnd("by"+i,h*2))%(h*1.2));ctx.strokeStyle="rgba(190,245,240,.12)";ctx.beginPath();ctx.arc(bx,by,1+rnd("br"+i,2.5),0,7);ctx.stroke()}}
function updateHud(){document.getElementById("watched").textContent=movies.length;document.getElementById("species").textContent=eco.discovered.length;document.getElementById("richness").textContent=Math.round(eco.environment.richness*100)+"%"}
function frame(t){cam.x+=(cam.targetX-cam.x)*.045;cam.y+=(cam.targetY-cam.y)*.045;background(t);eco.individuals.slice(-120).sort((a,b)=>O.hash(a.movie.id||a.movie.title)-O.hash(b.movie.id||b.movie.title)).forEach((p,i)=>drawCreature(p,i,t));requestAnimationFrame(frame)}
function addMovie(){const gs=["Drama","Horror","Adventure","Fantasy","Comedy","Crime","Science Fiction","Romance"],before=new Set(eco.discovered),n=movies.length+1,m={id:"demo-"+n,title:"Movie "+n,genres:[gs[n%gs.length]],rating:3+(n%5)*.5,year:1980+n%46};movies.push(m);localStorage.setItem("cinemap.ocean.movies",JSON.stringify(movies));eco=O.build(movies);updateHud();const s=O.speciesFor(m);if(!before.has(s.id)){const d=document.getElementById("discovery");document.getElementById("newSpecies").textContent=s.name;document.getElementById("newMovie").textContent=m.title;d.hidden=false;setTimeout(()=>d.hidden=true,2800)}}
c.addEventListener("pointerdown",e=>{drag={x:e.clientX,y:e.clientY,cx:cam.targetX,cy:cam.targetY};c.setPointerCapture(e.pointerId)});c.addEventListener("pointermove",e=>{if(!drag)return;cam.targetX=Math.max(-innerWidth*.35,Math.min(innerWidth*.35,drag.cx+e.clientX-drag.x));cam.targetY=Math.max(-innerHeight*.12,Math.min(innerHeight*.12,drag.cy+(e.clientY-drag.y)*.3))});c.addEventListener("pointerup",()=>drag=null);addEventListener("resize",resize);document.getElementById("demo").onclick=addMovie;
(async()=>{resize();movies=await enrich(readLocal());eco=O.build(movies);updateHud();requestAnimationFrame(frame)})()})();