import { POC_MODES,POC_STATES,DEFAULT_SEED,scenarioFromSearch } from './poc-config.js';
const {mode,scenario}=scenarioFromSearch(),stage=document.querySelector('#stage'),hud=document.querySelector('#hud'),modes=document.querySelector('#modes'),states=document.querySelector('#states');
const rejected={B:'REJECT — WebGPU feature detection was not a distinct renderer',C:'REJECT — asset-first profile reused A without a material renderer difference'};
const href=(m,s)=>`?${new URLSearchParams({mode:m,pocState:String(s),seed:scenario.seed||DEFAULT_SEED})}`;
POC_MODES.forEach(id=>{const a=document.createElement('a');a.href=href(id,scenario.state);a.textContent=rejected[id]?`${id} ×`:id;if(id===mode)a.className='active';modes.append(a)});POC_STATES.forEach(v=>{const a=document.createElement('a');a.href=href(mode,v);a.textContent=`${v}本`;if(v===scenario.state)a.className='active';states.append(a)});
const metrics={frames:[],longFrames:0,started:performance.now(),ready:0};let last=performance.now();function tick(now){const dt=now-last;last=now;if(dt<1000){metrics.frames.push(dt);if(dt>50)metrics.longFrames++;if(metrics.frames.length>360)metrics.frames.shift()}const s=[...metrics.frames].sort((a,b)=>a-b),med=s.length?s[s.length>>1]:0;metrics.medianFps=med?1000/med:0;hud.innerHTML=`<b>PoC ${mode} · ${scenario.state}本</b><br>seed ${scenario.seed}<br>FPS median ${metrics.medianFps.toFixed(0)} · long ${metrics.longFrames}<br>ready ${metrics.ready?metrics.ready.toFixed(0)+'ms':'…'}`;requestAnimationFrame(tick)}requestAnimationFrame(tick);
function seeded(i){const n=[...scenario.seed].reduce((a,c)=>a+c.charCodeAt(0),0)+scenario.state,x=Math.sin((i+1)*(n+17))*43758.5453;return x-Math.floor(x)}
function setupCanvas(){const canvas=document.createElement('canvas');stage.append(canvas);const ctx=canvas.getContext('2d',{alpha:false});let w=0,h=0;function resize(){const d=Math.min(devicePixelRatio||1,2);w=stage.clientWidth;h=stage.clientHeight;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}resize();addEventListener('resize',resize);return{ctx,size:()=>({w,h})}}
const depthLayers=[{z:.22,alpha:.28,speed:.15},{z:.48,alpha:.55,speed:.42},{z:.82,alpha:.9,speed:.78}];
function drawWaterVolume(ctx,w,h,now){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#176f78');g.addColorStop(.28,'#0b5360');g.addColorStop(.68,'#073843');g.addColorStop(1,'#061f2b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<6;i++){const x=w*(.05+i*.19)+Math.sin(now*.00018+i)*18,beam=ctx.createLinearGradient(x,0,x+80,h*.8);beam.addColorStop(0,'rgba(210,255,239,.12)');beam.addColorStop(1,'rgba(90,185,174,0)');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(x-20,0);ctx.bezierCurveTo(x+15,h*.25,x+25,h*.52,x+75,h*.82);ctx.lineTo(x+125,h*.82);ctx.bezierCurveTo(x+65,h*.5,x+65,h*.22,x+35,0);ctx.fill()}ctx.restore();const haze=ctx.createLinearGradient(0,h*.2,0,h);haze.addColorStop(0,'rgba(83,170,164,.02)');haze.addColorStop(1,'rgba(3,24,31,.34)');ctx.fillStyle=haze;ctx.fillRect(0,0,w,h)}
function drawSeabedTexture(ctx,w,h){const top=h*.73;const g=ctx.createLinearGradient(0,top,0,h);g.addColorStop(0,'#536b59');g.addColorStop(.35,'#394f43');g.addColorStop(1,'#1a302b');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,h);ctx.lineTo(0,top+10);for(let x=0;x<=w;x+=8){const y=top+Math.sin(x*.012)*7+Math.sin(x*.037+1.7)*3+Math.sin(x*.071)*1.5;ctx.lineTo(x,y)}ctx.lineTo(w,h);ctx.fill();for(let i=0;i<180;i++){const x=seeded(i+800)*w,y=top+seeded(i+1000)*(h-top),r=.3+seeded(i+1200)*2.2;ctx.fillStyle=`rgba(${95+seeded(i)*45},${105+seeded(i+3)*35},${82+seeded(i+7)*30},${.05+seeded(i+9)*.13})`;ctx.beginPath();ctx.ellipse(x,y,r*2.1,r,seeded(i+5)*3,0,7);ctx.fill()}for(let i=0;i<7;i++){const x=seeded(i+1400)*w,y=top+18+seeded(i+1450)*(h-top-30),rw=12+seeded(i+1500)*28,rh=6+seeded(i+1550)*13,rg=ctx.createRadialGradient(x-rw*.25,y-rh*.4,1,x,y,rw);rg.addColorStop(0,'#65776b');rg.addColorStop(.55,'#3c5148');rg.addColorStop(1,'#213832');ctx.fillStyle=rg;ctx.beginPath();ctx.ellipse(x,y,rw,rh,seeded(i+1600)*.7-.35,0,7);ctx.fill()}}
function drawVegetation(ctx,w,h,now,maturity){const top=h*.73,count=Math.round(3+maturity*32);for(let i=0;i<count;i++){const x=seeded(i+1700)*w,base=top+18+seeded(i+1750)*(h-top-20),len=12+seeded(i+1800)*(22+maturity*70),sway=Math.sin(now*.0011+i*1.9)*(3+seeded(i)*6),width=2+seeded(i+1850)*6;ctx.strokeStyle=`rgba(${30+seeded(i)*35},${92+seeded(i+2)*55},${62+seeded(i+5)*28},${.45+seeded(i+8)*.35})`;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,base);ctx.bezierCurveTo(x-sway*.5,base-len*.35,x+sway,base-len*.68,x+sway*.6,base-len);ctx.stroke();if(maturity>.35&&i%4===0){ctx.fillStyle='rgba(64,118,79,.52)';for(let j=1;j<4;j++){const yy=base-len*j*.2,side=j%2?1:-1;ctx.beginPath();ctx.ellipse(x+sway*j*.12+side*5,yy,7,2.4,side*.55,0,7);ctx.fill()}}}}
function drawNaturalFish(ctx,x,y,s,t,alpha,phase){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.globalAlpha=alpha;const tail=Math.sin(phase)*3,body=ctx.createLinearGradient(-24,-7,22,8);body.addColorStop(0,`hsl(${178+t*24} 30% 30%)`);body.addColorStop(.42,`hsl(${184+t*22} 42% 55%)`);body.addColorStop(.75,`hsl(${190+t*16} 35% 45%)`);body.addColorStop(1,`hsl(${181+t*20} 28% 27%)`);ctx.fillStyle=body;ctx.beginPath();ctx.moveTo(-21,0);ctx.bezierCurveTo(-14,-10,4,-12,19,-4);ctx.bezierCurveTo(24,-1,23,3,17,6);ctx.bezierCurveTo(2,12,-15,8,-21,0);ctx.fill();ctx.beginPath();ctx.moveTo(-19,0);ctx.bezierCurveTo(-30,-12-tail,-34,-11-tail,-31,0);ctx.bezierCurveTo(-34,11+tail,-29,12+tail,-19,0);ctx.fill();ctx.fillStyle='rgba(137,191,181,.48)';ctx.beginPath();ctx.moveTo(-1,-8);ctx.quadraticCurveTo(4,-18,10,-7);ctx.quadraticCurveTo(5,-9,-1,-8);ctx.fill();ctx.beginPath();ctx.moveTo(0,7);ctx.quadraticCurveTo(7,15,12,5);ctx.fill();ctx.fillStyle='rgba(238,255,246,.8)';ctx.beginPath();ctx.arc(15,-2.5,1.35,0,7);ctx.fill();ctx.fillStyle='rgba(4,16,18,.9)';ctx.beginPath();ctx.arc(15.3,-2.5,.65,0,7);ctx.fill();ctx.restore()}
function mountLayered2D(){const {ctx,size}=setupCanvas(),maturity=scenario.maturity,count=Math.min(48,Math.round(2+maturity*36+scenario.habitat.schools*1.5)),school=scenario.state>=30;function draw(now){const {w,h}=size();drawWaterVolume(ctx,w,h,now);for(let i=0;i<70;i++){const z=.2+seeded(i+2000)*.8,x=(seeded(i+2050)*w+now*.003*z*(1+i%3))%w,y=seeded(i+2100)*h*.72;ctx.globalAlpha=.03+.12*z;ctx.fillStyle='#dffdf4';ctx.beginPath();ctx.arc(x,y,.35+1.5*z,0,7);ctx.fill()}ctx.globalAlpha=1;drawSeabedTexture(ctx,w,h);drawVegetation(ctx,w,h,now,maturity);for(let i=0;i<count;i++){const layer=depthLayers[i%depthLayers.length],group=school?Math.floor(i/7):i,leaderY=h*(.16+seeded(group+2200)*.46),x=(seeded(i+2250)*(w+100)+now*(.006+layer.speed*.014))%(w+120)-60,y=leaderY+(seeded(i+2300)-.5)*(school?36:120),s=(.32+seeded(i+2350)*.72)*(.55+layer.z*.65);drawNaturalFish(ctx,x,y,s,seeded(i+2400),layer.alpha,now*.004+i)}if(scenario.state>=100){const n=scenario.state>=500?4:2;for(let i=0;i<n;i++)drawNaturalFish(ctx,(w*.15+i*w*.28+now*.009)%(w+140)-70,h*(.28+i*.08),1.2+i*.12,.7,.72,now*.002+i)}const fog=ctx.createLinearGradient(0,0,w,0);fog.addColorStop(0,'rgba(8,50,57,.14)');fog.addColorStop(.5,'rgba(8,50,57,0)');fog.addColorStop(1,'rgba(8,50,57,.12)');ctx.fillStyle=fog;ctx.fillRect(0,0,w,h);requestAnimationFrame(draw)}requestAnimationFrame(draw);return Promise.resolve()}
function mountIllustrated2D(){const {ctx,size}=setupCanvas();function draw(now){const {w,h}=size();drawWaterVolume(ctx,w,h,now);drawSeabedTexture(ctx,w,h);drawVegetation(ctx,w,h,now,scenario.maturity*.8);requestAnimationFrame(draw)}requestAnimationFrame(draw);return Promise.resolve()}
async function mountA(){const mod=await import('../renderer/dist/ocean-renderer.js');const host=document.createElement('div');host.style.cssText='width:100%;height:100%';stage.append(host);await mod.mountOcean(host,scenario)}async function mountD(){return mountLayered2D()}async function mountE(){return mountIllustrated2D()}const reject=()=>{throw new Error(rejected[mode])},mounts={A:mountA,B:reject,C:reject,D:mountD,E:mountE};
try{await mounts[mode]();metrics.ready=performance.now()-metrics.started;document.documentElement.dataset.pocReady='true'}catch(error){metrics.ready=performance.now()-metrics.started;hud.innerHTML=`<b>PoC ${mode} FAIL</b><br>${error.message}`;hud.classList.add('fail');document.documentElement.dataset.pocReady='false';console.error(error)}window.__OCEAN_POC__={mode,scenario,metrics,rejected};