import { POC_MODES, POC_STATES, DEFAULT_SEED, scenarioFromSearch } from './poc-config.js';

const { mode, scenario } = scenarioFromSearch();
const stage = document.querySelector('#stage');
const hud = document.querySelector('#hud');
const modes = document.querySelector('#modes');
const states = document.querySelector('#states');
const rejected={B:'REJECT — WebGPU feature detection was not a distinct renderer',C:'REJECT — asset-first profile reused A without a material renderer difference'};

function href(nextMode,nextState){const q=new URLSearchParams({mode:nextMode,pocState:String(nextState),seed:scenario.seed||DEFAULT_SEED});return `?${q}`}
POC_MODES.forEach(id=>{const a=document.createElement('a');a.href=href(id,scenario.state);a.textContent=rejected[id]?`${id} ×`:id;if(id===mode)a.className='active';modes.append(a)});
POC_STATES.forEach(value=>{const a=document.createElement('a');a.href=href(mode,value);a.textContent=`${value}本`;if(value===scenario.state)a.className='active';states.append(a)});

const metrics={frames:[],longFrames:0,started:performance.now(),ready:0};let last=performance.now();
function tick(now){const dt=now-last;last=now;if(dt<1000){metrics.frames.push(dt);if(dt>50)metrics.longFrames+=1;if(metrics.frames.length>360)metrics.frames.shift()}const sorted=[...metrics.frames].sort((a,b)=>a-b);const median=sorted.length?sorted[Math.floor(sorted.length/2)]:0;metrics.medianFps=median?1000/median:0;hud.innerHTML=`<b>PoC ${mode} · ${scenario.state}本</b><br>seed ${scenario.seed}<br>FPS median ${metrics.medianFps.toFixed(0)} · long ${metrics.longFrames}<br>ready ${metrics.ready?metrics.ready.toFixed(0)+'ms':'…'}`;requestAnimationFrame(tick)}requestAnimationFrame(tick);
function seeded(i){const n=[...scenario.seed].reduce((a,c)=>a+c.charCodeAt(0),0)+scenario.state;const x=Math.sin((i+1)*(n+17))*43758.5453;return x-Math.floor(x)}
function setupCanvas(){const canvas=document.createElement('canvas');stage.append(canvas);const ctx=canvas.getContext('2d');let w=0,h=0,dpr=1;const resize=()=>{dpr=Math.min(devicePixelRatio||1,2);w=stage.clientWidth;h=stage.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)};resize();addEventListener('resize',resize);return{canvas,ctx,size:()=>({w,h})}}
function fish(ctx,x,y,s,t,alpha=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.globalAlpha=alpha;const g=ctx.createLinearGradient(-18,-4,18,4);g.addColorStop(0,`hsl(${178+t*35} 38% 38%)`);g.addColorStop(.55,`hsl(${184+t*28} 55% 66%)`);g.addColorStop(1,`hsl(${170+t*20} 28% 34%)`);ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,0,18,7.5,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-15,0);ctx.lineTo(-29,-10);ctx.lineTo(-25,9);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(235,255,247,.8)';ctx.beginPath();ctx.arc(10,-2,1.2,0,7);ctx.fill();ctx.restore()}
function mountLayered2D(){const {ctx,size}=setupCanvas();const count=Math.min(42,Math.round(scenario.stats.species*1.35+scenario.habitat.schools*2));function draw(now){const {w,h}=size();const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0a6871');g.addColorStop(.45,'#0a4650');g.addColorStop(1,'#071f2b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let band=0;band<5;band++){ctx.globalAlpha=.055+band*.018;ctx.fillStyle='#bfeee2';ctx.beginPath();ctx.moveTo(w*(.08+band*.19),0);ctx.lineTo(w*(.2+band*.18),0);ctx.lineTo(w*(.45+band*.15),h*.78);ctx.lineTo(w*(.28+band*.14),h*.78);ctx.closePath();ctx.fill()}ctx.globalAlpha=1;for(let i=0;i<55;i++){const z=.35+seeded(i+10)*.65,x=(seeded(i)*w+now*.004*(1+i%3))%w,y=seeded(i+60)*h;ctx.globalAlpha=.05+.16*z;ctx.fillStyle='#d9fff4';ctx.beginPath();ctx.arc(x,y,.5+2*z,0,7);ctx.fill()}ctx.globalAlpha=1;const floor=h*.76;const sand=ctx.createLinearGradient(0,floor,0,h);sand.addColorStop(0,'#405c50');sand.addColorStop(1,'#182f2b');ctx.fillStyle=sand;ctx.beginPath();ctx.moveTo(0,floor);for(let x=0;x<=w;x+=18)ctx.lineTo(x,floor+Math.sin(x*.019)*8+Math.sin(x*.053)*3);ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.fill();const growth=scenario.maturity;for(let i=0;i<Math.round(5+growth*24);i++){const x=seeded(i+130)*w,base=h*(.78+seeded(i+160)*.18),len=16+seeded(i+190)*(30+growth*62);ctx.strokeStyle=`rgba(${42+Math.round(seeded(i)*35)},${102+Math.round(seeded(i+3)*55)},${65+Math.round(seeded(i+9)*30)},.78)`;ctx.lineWidth=1.4+seeded(i+6)*4;ctx.beginPath();ctx.moveTo(x,base);ctx.bezierCurveTo(x+Math.sin(now*.001+i)*8,base-len*.35,x+Math.sin(now*.0012+i)*12,base-len*.7,x+Math.sin(now*.0014+i)*9,base-len);ctx.stroke()}for(let i=0;i<count;i++){const depth=.35+seeded(i+280)*.65,x=(seeded(i+230)*w+now*(.006+seeded(i)*.012)*depth)%(w+80)-40,y=h*(.14+seeded(i+260)*.53),s=(.3+seeded(i+290)*.72)*depth;fish(ctx,x,y,s,seeded(i+310),.45+.55*depth)}ctx.globalCompositeOperation='screen';const glow=ctx.createRadialGradient(w*.52,0,10,w*.52,0,h*.92);glow.addColorStop(0,'rgba(198,255,238,.2)');glow.addColorStop(.45,'rgba(80,188,174,.05)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over';requestAnimationFrame(draw)}requestAnimationFrame(draw);return Promise.resolve()}
function mountIllustrated2D(){const {ctx,size}=setupCanvas();const count=Math.min(30,Math.round(scenario.stats.species+scenario.habitat.schools*1.5));function draw(now){const {w,h}=size();const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#092f45');g.addColorStop(.5,'#0b5360');g.addColorStop(1,'#061d2a');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);for(let layer=0;layer<3;layer++){ctx.globalAlpha=.12-layer*.025;ctx.fillStyle=layer===0?'#1f6159':'#17473f';ctx.beginPath();ctx.moveTo(0,h);for(let x=0;x<=w;x+=32){const y=h*(.72+layer*.08)+Math.sin(x*.018+layer)*18+seeded(x+layer)*10;ctx.lineTo(x,y)}ctx.lineTo(w,h);ctx.fill()}ctx.globalAlpha=1;for(let i=0;i<count;i++){const par=.4+seeded(i+40)*.6;fish(ctx,(seeded(i)*w+now*.007*par)%(w+80)-40,h*(.12+seeded(i+90)*.55),(.35+seeded(i+120)*.75)*par,seeded(i+150),.55+.45*par)}ctx.globalAlpha=.12;ctx.strokeStyle='#c7f6e9';for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(-30+i*w/7,0);ctx.lineTo(w*.2+i*w/7,h*.8);ctx.stroke()}ctx.globalAlpha=1;requestAnimationFrame(draw)}requestAnimationFrame(draw);return Promise.resolve()}
async function mountA(){const mod=await import('../renderer/dist/ocean-renderer.js');const host=document.createElement('div');host.style.cssText='width:100%;height:100%';stage.append(host);await mod.mountOcean(host,scenario)}
async function mountD(){return mountLayered2D()}
async function mountE(){return mountIllustrated2D()}
const reject=()=>{throw new Error(rejected[mode])};
const mounts={A:mountA,B:reject,C:reject,D:mountD,E:mountE};
try{await mounts[mode]();metrics.ready=performance.now()-metrics.started;document.documentElement.dataset.pocReady='true'}catch(error){metrics.ready=performance.now()-metrics.started;hud.innerHTML=`<b>PoC ${mode} FAIL</b><br>${error.message}`;hud.classList.add('fail');document.documentElement.dataset.pocReady='false';console.error(error)}
window.__OCEAN_POC__={mode,scenario,metrics,rejected};