import { POC_MODES,POC_STATES,DEFAULT_SEED,scenarioFromSearch } from './poc-config.js';
import { loadDV3Assets } from './d-v3-assets.js';
const {mode,scenario}=scenarioFromSearch(),stage=document.querySelector('#stage'),hud=document.querySelector('#hud'),modes=document.querySelector('#modes'),states=document.querySelector('#states');
const rejected={B:'REJECT — not distinct',C:'REJECT — not distinct'};const href=(m,s)=>`?${new URLSearchParams({mode:m,pocState:String(s),seed:scenario.seed||DEFAULT_SEED})}`;
POC_MODES.forEach(id=>{const a=document.createElement('a');a.href=href(id,scenario.state);a.textContent=rejected[id]?`${id} ×`:id;if(id===mode)a.className='active';modes.append(a)});POC_STATES.forEach(v=>{const a=document.createElement('a');a.href=href(mode,v);a.textContent=`${v}本`;if(v===scenario.state)a.className='active';states.append(a)});
const metrics={frames:[],longFrames:0,started:performance.now(),ready:0};let last=performance.now();function tick(now){const dt=now-last;last=now;if(dt<1000){metrics.frames.push(dt);if(dt>50)metrics.longFrames++;if(metrics.frames.length>360)metrics.frames.shift()}const s=[...metrics.frames].sort((a,b)=>a-b),med=s.length?s[s.length>>1]:0;metrics.medianFps=med?1000/med:0;hud.innerHTML=`<b>PoC ${mode} · ${scenario.state}本</b><br>D-v3 sprite compositor<br>FPS median ${metrics.medianFps.toFixed(0)} · long ${metrics.longFrames}<br>ready ${metrics.ready?metrics.ready.toFixed(0)+'ms':'…'}`;requestAnimationFrame(tick)}requestAnimationFrame(tick);
function seeded(i){const n=[...scenario.seed].reduce((a,c)=>a+c.charCodeAt(0),0)+scenario.state,x=Math.sin((i+1)*(n+17))*43758.5453;return x-Math.floor(x)}
function setupCanvas(){const canvas=document.createElement('canvas');stage.append(canvas);const ctx=canvas.getContext('2d',{alpha:false});let w=0,h=0;function resize(){const d=Math.min(devicePixelRatio||1,2);w=stage.clientWidth;h=stage.clientHeight;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}resize();addEventListener('resize',resize);return{ctx,size:()=>({w,h})}}
function background(ctx,w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#176e78');g.addColorStop(.3,'#0b5260');g.addColorStop(.72,'#073640');g.addColorStop(1,'#061d28');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
async function mountLayered2D(){const assets=await loadDV3Assets(),{ctx,size}=setupCanvas(),m=scenario.maturity,count=Math.min(45,Math.round(3+m*34+scenario.habitat.schools));function draw(now){const {w,h}=size();background(ctx,w,h);ctx.globalAlpha=.58;for(let i=0;i<3;i++){const x=-70+i*w*.42+Math.sin(now*.00012+i)*15;ctx.drawImage(assets.caustic,x,-30,w*.72,h*.82)}ctx.globalAlpha=1;
// seabed: textured micro-grain with no geometric horizon edge
const top=h*.73,g=ctx.createLinearGradient(0,top-35,0,h);g.addColorStop(0,'rgba(55,76,65,0)');g.addColorStop(.18,'#526655');g.addColorStop(1,'#182e29');ctx.fillStyle=g;ctx.fillRect(0,top-35,w,h-top+35);for(let i=0;i<240;i++){const x=seeded(i+700)*w,y=top-10+seeded(i+900)*(h-top+10);ctx.globalAlpha=.035+seeded(i)*.1;ctx.fillStyle='#b0a782';ctx.fillRect(x,y,.5+seeded(i+4)*2,.5+seeded(i+5)*1.3)}ctx.globalAlpha=1;
// static-looking habitat sprites; irregular scale/crop prevents copy pattern
const rocks=Math.round(2+m*6);for(let i=0;i<rocks;i++){const rw=70+seeded(i+1200)*110,rh=rw*.58,x=seeded(i+1250)*(w-rw),y=top+20+seeded(i+1300)*(h-top-rh*.55);ctx.globalAlpha=.62+.3*seeded(i);ctx.drawImage(assets.rock,x,y,rw,rh)}ctx.globalAlpha=1;const plants=Math.round(2+m*20);for(let i=0;i<plants;i++){const ph=38+seeded(i+1400)*(45+m*85),pw=ph*.36,x=seeded(i+1450)*w,y=h-ph+seeded(i+1500)*18,sway=Math.sin(now*.0007+i)*2;ctx.globalAlpha=.45+.4*seeded(i+1510);ctx.drawImage(assets.grass,x+sway,y,pw,ph)}ctx.globalAlpha=1;
// fish are cached image sprites; only transform/drawImage happens per frame
for(let i=0;i<count;i++){const z=.28+seeded(i+1800)*.72,school=scenario.state>=30,group=school?Math.floor(i/7):i,fw=(42+seeded(i+1850)*74)*(.62+z*.5),fh=fw*.5,x=(seeded(i+1900)*(w+fw*2)+now*(.006+z*.013))%(w+fw*2)-fw,y=h*(.14+seeded(group+1950)*.48)+(seeded(i+2000)-.5)*(school?42:130);ctx.globalAlpha=.34+z*.62;ctx.drawImage(assets.fish[i%assets.fish.length],x,y,fw,fh)}ctx.globalAlpha=1;
// particulate water depth cue
for(let i=0;i<48;i++){const z=.2+seeded(i+2200)*.8,x=(seeded(i+2250)*w+now*.002*z)%w,y=seeded(i+2300)*h*.75;ctx.globalAlpha=.025+.08*z;ctx.fillStyle='#e0fff6';ctx.fillRect(x,y,1+z,1+z)}ctx.globalAlpha=1;const fog=ctx.createLinearGradient(0,0,w,0);fog.addColorStop(0,'rgba(5,41,48,.16)');fog.addColorStop(.5,'rgba(5,41,48,0)');fog.addColorStop(1,'rgba(5,41,48,.14)');ctx.fillStyle=fog;ctx.fillRect(0,0,w,h);requestAnimationFrame(draw)}requestAnimationFrame(draw)}
function mountE(){return mountLayered2D()}async function mountA(){const mod=await import('../renderer/dist/ocean-renderer.js');const host=document.createElement('div');host.style.cssText='width:100%;height:100%';stage.append(host);await mod.mountOcean(host,scenario)}const reject=()=>{throw new Error(rejected[mode])},mounts={A:mountA,B:reject,C:reject,D:mountLayered2D,E:mountE};
try{await mounts[mode]();metrics.ready=performance.now()-metrics.started;document.documentElement.dataset.pocReady='true'}catch(error){metrics.ready=performance.now()-metrics.started;hud.innerHTML=`<b>PoC ${mode} FAIL</b><br>${error.message}`;hud.classList.add('fail');document.documentElement.dataset.pocReady='false';console.error(error)}window.__OCEAN_POC__={mode,scenario,metrics,rejected};
