'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=m=>String(m.id||m.title), safe=u=>{try{const x=new URL(u);return x.protocol==='https:'?x.href:''}catch{return ''}};
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
let state=read('cinema-night-shelf',{});if(!state||Array.isArray(state)||typeof state!=='object')state={};
let movies=[],availability={},plans=[],offset=0,startAt=null,loaded=false;
const clock=d=>d.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'}),dateLabel=d=>d.toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
function save(){try{localStorage.setItem('cinema-night-shelf',JSON.stringify(state))}catch{$('#status').textContent='このブラウザでは保存できません。ページを閉じるまで保持します。'}}
function providers(m){const a=availability[key(m)];return Array.isArray(a?.flatrate)?a.flatrate:[]}
function profile(){const r=read('cinema-now-dna-ratings',[]),g=new Map();if(!Array.isArray(r))return g;for(const x of r){if(x.r<4)continue;const m=movies.find(m=>x.id?String(x.id)===String(m.id):x.title===m.title);for(const z of m?.genres||[])g.set(z,(g.get(z)||0)+1)}return g}
function connection(a,b){if(a.director&&a.director===b.director)return a.director+'監督を2本で見比べる';const shared=(a.genres||[]).filter(g=>(b.genres||[]).includes(g));return shared.length?shared.slice(0,2).join(' × ')+'でつながる2本。物語の運び方を見比べてみよう。':''}
function generate(){
 if(!loaded)return;startAt=new Date($('#start').value);const parts=$('#end').value.split(':').map(Number);if(!Number.isFinite(+startAt)||parts.length!==2)return;
 const end=new Date(startAt);end.setHours(parts[0],parts[1],0,0);if(end<startAt)end.setDate(end.getDate()+1);const budget=Math.floor((end-startAt)/60000);
 plans=[];offset=0;if(budget<=0||budget>720){$('#status').textContent='終了は開始から12時間以内にしてください。開始より早い時刻は翌日として扱います。';render();return}
 const services=[...document.querySelectorAll('#services input:checked')].map(x=>x.value),p=profile(),direction=$('#direction').value;
 $('#dnaInfo').textContent=p.size?'映画DNAで★4以上を付けた作品のジャンルを使用。好みの一歩外へは、共通点を残しながら新しいジャンルを優先します。':'映画DNAを診断すると、好みに合わせた選び方が使えます。現在は評価と上映時間で提案します。';
 const rated=read('cinema-now-dna-ratings',[]),seen=new Set(Array.isArray(rated)?rated.map(x=>String(x.id||x.title)):[]);
 const pool=movies.filter(m=>Number(m.runtime)>0&&m.runtime<=budget&&state[key(m)]?.status!=='watched'&&!seen.has(key(m))&&(!$('#only').checked||providers(m).some(s=>services.includes(s))));
 const score=m=>{const gs=m.genres||[],common=gs.filter(g=>p.has(g)).length,novel=gs.filter(g=>!p.has(g)).length;return Number(m.score||0)*Math.min(1,Number(m.votes||0)/100)+(state[key(m)]?.status==='saved'?2:0)+(p.size&&direction==='familiar'?common*2:0)+(p.size&&direction==='explore'?(common?2:0)+novel*2-common:0)};
 pool.sort((a,b)=>score(b)-score(a));
 if($('#format').value==='two'){for(let i=0;i<pool.length;i++)for(let j=i+1;j<pool.length;j++){const a=pool[i],b=pool[j],duration=Number(a.runtime)+Number(b.runtime)+10,why=connection(a,b);if(duration<=budget&&why)plans.push({items:[a,b],duration,why,score:score(a)+score(b)+(a.director&&a.director===b.director?3:0)})}}
 else plans=pool.map(m=>({items:[m],duration:Number(m.runtime),why:direction==='explore'&&p.size?'好みの共通点と、まだ評価していないジャンルから。':direction==='familiar'&&p.size?'映画DNAで高評価だったジャンルを優先。':'上映時間と、評価件数を考慮したTMDB評価から。',score:score(m)}));
 plans.sort((a,b)=>b.score-a.score||b.duration-a.duration);
 // Keep the first alternatives diverse, so a single popular title does not occupy every slot.
 const used=new Set(),first=[],rest=[];for(const p of plans){if(p.items.every(m=>!used.has(key(m)))){first.push(p);p.items.forEach(m=>used.add(key(m)))}else rest.push(p)}plans=[...first,...rest];
 $('#status').textContent=budget+'分の枠 · '+pool.length+'作品が条件に一致 · '+plans.length+'通りのプログラム';render();
}
function actions(m){const k=esc(key(m)),s=state[key(m)]?.status;return '<div class="actions"><button data-save="'+k+'" aria-pressed="'+(s==='saved')+'">'+(s==='saved'?'保存を解除':'＋ あとで観る')+'</button><button data-watch="'+k+'">'+(s==='watched'?'未鑑賞に戻す':'鑑賞済みにする')+'</button><a target="_blank" rel="noopener noreferrer" href="https://filmarks.com/search/movies?q='+encodeURIComponent(m.title)+'">Filmarksで探す ↗</a></div>'}
function movieHtml(m,time){const ps=providers(m),a=availability[key(m)],source=safe(a?.source_url)||('https://www.themoviedb.org/movie/'+encodeURIComponent(m.id)+'/watch?locale=JP');return '<article class="movie">'+(safe(m.poster)?'<img class="poster" src="'+esc(safe(m.poster))+'" alt="" loading="lazy">':'<div class="poster"></div>')+'<div><div class="meta">'+esc(time)+' · '+m.runtime+'分</div><h3>'+esc(m.title)+'</h3><div class="meta">'+esc((m.genres||[]).join(' / '))+' · TMDB '+(m.score?'★'+Number(m.score).toFixed(1):'評価なし')+'（'+Number(m.votes||0).toLocaleString()+'件）</div><div class="meta">'+(ps.length?'見放題：'+esc(ps.join(' / ')):'見放題の確認情報なし')+'</div>'+(a?.checked_at?'<div class="meta">確認：'+esc(dateLabel(new Date(a.checked_at)))+'</div>':'')+(m.id?'<a target="_blank" rel="noopener noreferrer" href="'+esc(source)+'">配信先を確認 ↗</a>':'')+actions(m)+'</div></article>'}
function render(){const rows=plans.slice(offset,offset+3);$('#shuffle').hidden=plans.length<=3;$('#results').innerHTML=rows.length?rows.map((p,i)=>{let t=+startAt;return '<article class="program"><div class="programTop"><b>PROGRAM '+String(offset+i+1).padStart(2,'0')+'</b><span>'+esc(dateLabel(startAt))+' → '+esc(dateLabel(new Date(t+p.duration*60000)))+' · '+p.duration+'分</span></div><div class="bridge">'+esc(p.why)+'</div>'+p.items.map((m,j)=>{let s=clock(new Date(t));t+=Number(m.runtime)*60000;const out=movieHtml(m,s+'–'+clock(new Date(t)));if(j<p.items.length-1){t+=600000;return out+'<div class="bridge">10分休憩 · 次の作品では共通点と違いに注目</div>'}return out}).join('')+'<div class="actions"><button data-calendar="'+(offset+i)+'">予定に入れる（.ics）</button><button data-share="'+(offset+i)+'">プログラムを共有</button></div></article>'}).join(''):'<div class="empty">条件に合うプログラムがありません。時間を広げるか、見放題の絞り込みを変更してください。上映時間が不明な作品と鑑賞済み作品は除外しています。</div>';renderShelf();}
function renderShelf(){const s=$('#shelfMode').value,rows=Object.values(state).filter(x=>x?.status===s&&x.movie);$('#shelf').innerHTML=rows.length?rows.map(x=>'<div class="shelfRow"><b>'+esc(x.movie.title)+'</b>'+actions(x.movie)+'</div>').join(''):'<p class="note">'+(s==='saved'?'気になる作品の「あとで観る」で、ここに保存できます。':'鑑賞済みにした作品がここに残ります。')+'</p>'}
function icsEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function calendar(p){const dt=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');let t=+startAt;const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Cinema Now//Film Night//JA','CALSCALE:GREGORIAN'];for(const m of p.items){const end=t+Number(m.runtime)*60000;lines.push('BEGIN:VEVENT','UID:'+key(m)+'-'+t+'@cinema-now','DTSTAMP:'+dt(new Date()),'DTSTART:'+dt(new Date(t)),'DTEND:'+dt(new Date(end)),'SUMMARY:'+icsEscape(m.title),'DESCRIPTION:'+icsEscape('CINEMA NOWの鑑賞プラン。配信状況は再生前に確認してください。'),'END:VEVENT');t=end+600000}lines.push('END:VCALENDAR');const folded=lines.map(line=>{let rows=[],row='',n=0;for(const ch of line){let size=new TextEncoder().encode(ch).length;if(n+size>73){rows.push(row);row=' ';n=1}row+=ch;n+=size}rows.push(row);return rows.join('\r\n')}).join('\r\n')+'\r\n';const url=URL.createObjectURL(new Blob([folded],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='cinema-night.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
async function share(p){const text=dateLabel(startAt)+'からの映画プラン\n'+p.items.map(m=>m.title+'（'+m.runtime+'分）').join(' → ')+(p.items.length>1?'\n休憩10分込み':'')+'\n'+p.why+'\n'+location.href.split('#')[0];try{if(navigator.share){await navigator.share({title:'映画の夜をつくる',text});return}await navigator.clipboard.writeText(text);$('#status').textContent='プログラムをコピーしました。'}catch(e){if(e.name!=='AbortError')prompt('このプログラムをコピーしてください',text)}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.calendar!==undefined)return calendar(plans[+b.dataset.calendar]);if(b.dataset.share!==undefined)return share(plans[+b.dataset.share]);const k=b.dataset.save||b.dataset.watch;if(!k)return;const m=movies.find(m=>key(m)===k)||state[k]?.movie;if(!m)return;if(b.dataset.save){if(state[k]?.status==='saved')delete state[k];else state[k]={status:'saved',movie:m}}else state[k]={status:state[k]?.status==='watched'?'saved':'watched',movie:m};save();generate();});
$('#settings').addEventListener('submit',e=>{e.preventDefault();generate()});$('#settings').addEventListener('change',()=>{if(loaded&&$('#settings').checkValidity())generate()});$('#shuffle').onclick=()=>{offset=offset+3>=plans.length?0:offset+3;render()};$('#shelfMode').onchange=renderShelf;
async function boot(){const d=new Date();d.setSeconds(0,0);const local=new Date(+d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#start').value=local;$('#end').value=clock(new Date(+d+150*60000));try{const [mr,ar]=await Promise.all([fetch('data/movies.json'),fetch('data/availability.json').catch(()=>null)]);if(!mr.ok)throw Error();const data=await mr.json(),seen=new Set();movies=(data.movies||[]).filter(m=>{const k=key(m);if(seen.has(k)||!m.title||m.event==='festival')return false;seen.add(k);return true});let warning='';if(ar?.ok){availability=(await ar.json()).movies||{}}else warning='配信情報を取得できません。再読み込みするか、見放題の絞り込みを外してください。';const names=[...new Set(['Netflix','Prime Video','Disney+','U-NEXT','Hulu',...Object.values(availability).flatMap(a=>a.flatrate||[])])].sort();$('#services').innerHTML=names.map(s=>'<label><input type="checkbox" value="'+esc(s)+'"> '+esc(s)+'</label>').join('');loaded=true;$('#make').disabled=false;$('#results').innerHTML='<div class="empty">サブスクを選ぶと、時間内に観られる候補を提案します。</div>';$('#status').textContent=warning||movies.length+'作品から、あなたの夜に合うプログラムを。';renderShelf();}catch{$('#status').innerHTML='作品を読み込めませんでした。<a href="night.html">再読み込み</a>';renderShelf()}}
boot();
