const assert=require('assert'),fs=require('fs'),path=require('path');const ROOT=path.join(__dirname,'..');
const immersive=fs.readFileSync(path.join(ROOT,'preview/ocean/js/ocean-immersive.js'),'utf8');const renderer=fs.readFileSync(path.join(ROOT,'preview/ocean/js/ocean-v8.js'),'utf8');const geometry=JSON.parse(fs.readFileSync(path.join(ROOT,'preview/ocean/assets/bsd/SmallFishA.json'),'utf8'));const backdrop=path.join(ROOT,'preview/ocean/assets/generated/ocean-cinematic-bg.webp');
assert.ok(immersive.includes("VERSION='0.8.1'")&&immersive.includes("CACHE='10'"),'visible build is v0.8.1 with fresh cache');
assert.ok(immersive.includes('ocean-v8.js')&&immersive.includes('CinemapOceanV8'),'immersive view mounts v0.8 renderer');
assert.ok(immersive.includes('brightness(1.55)'),'foreground 3D life is lifted from silhouette-black rendering');
assert.ok(renderer.includes("getContext('webgl2'")&&renderer.includes('SmallFishA.json')&&renderer.includes('smallfish.webp'),'v0.8 keeps locally vendored textured 3D fish');
assert.ok(renderer.includes('ocean-cinematic-bg.webp'),'v0.8 has a dedicated cinematic reef backdrop');
assert.ok(fs.existsSync(backdrop)&&fs.statSync(backdrop).size>8000,'cinematic backdrop retains enough local detail for iPhone presentation');
assert.ok(renderer.includes('tail*tail')&&renderer.includes('requestAnimationFrame')&&renderer.includes('pointermove'),'fish remain animated and scene remains explorable');
assert.ok(renderer.includes('population=clamp')&&renderer.includes('org.length'),'visible population still derives from ecosystem growth');
assert.ok(geometry.position.length>300&&geometry.normal.length===geometry.position.length&&geometry.uv.length>200,'fish mesh is real textured geometry');
assert.ok(fs.existsSync(path.join(ROOT,'preview/ocean/assets/bsd/LICENSE-WebGLSamples.txt')),'BSD provenance is retained');
assert.ok(!renderer.includes('http://')&&!renderer.includes('https://'),'renderer makes no external runtime request');
assert.ok(!renderer.includes('cosmosHalo')&&!renderer.includes('fish-atlas'),'rejected halo/sprite treatments stay absent');
console.log('Ocean cinematic WebGL2 v0.8.1 contract tests passed');
