const assert = require('assert');
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const immersive = fs.readFileSync(path.join(ROOT, 'preview/ocean/js/ocean-immersive.js'), 'utf8');
const renderer = fs.readFileSync(path.join(ROOT, 'preview/ocean/js/ocean-3d.js'), 'utf8');
const geometry = JSON.parse(fs.readFileSync(path.join(ROOT, 'preview/ocean/assets/bsd/SmallFishA.json'), 'utf8'));
assert.ok(immersive.includes("VERSION='0.7.0'"), 'visible/runtime version is v0.7.0');
assert.ok(immersive.includes("CACHE='8'"), 'v0.7 renderer uses a fresh cache key');
assert.ok(immersive.includes('ocean-3d.js') && immersive.includes('CinemapOcean3D'), 'immersive view mounts the textured 3D renderer');
assert.ok(renderer.includes("getContext('webgl2'"), 'Ocean v0.7 uses WebGL2');
assert.ok(renderer.includes('SmallFishA.json') && renderer.includes('smallfish.webp'), '3D renderer uses locally vendored geometry and texture');
assert.ok(renderer.includes('aNormal') && renderer.includes('aUV'), 'fish use normals and UVs rather than primitive silhouettes');
assert.ok(renderer.includes('uBend') && renderer.includes('tail*tail'), 'fish mesh bends at the tail in the vertex shader');
assert.ok(renderer.includes('fog') && renderer.includes('rays'), 'water depth and light shafts are shader-driven');
assert.ok(renderer.includes('requestAnimationFrame') && renderer.includes('pointermove'), 'scene remains alive and explorable');
assert.ok(geometry.position.length > 300 && geometry.normal.length === geometry.position.length && geometry.uv.length > 200, 'vendored fish mesh is real textured geometry');
assert.ok(fs.existsSync(path.join(ROOT, 'preview/ocean/assets/bsd/LICENSE-WebGLSamples.txt')), 'BSD provenance is retained');
assert.ok(!renderer.includes('http://') && !renderer.includes('https://'), 'renderer makes no runtime external request');
assert.ok(!renderer.includes('cosmosHalo') && !renderer.includes('fish-atlas'), 'rejected halo/sprite treatments stay absent');
console.log('Ocean textured WebGL2 v0.7.0 contract tests passed');
