const assert=require('assert'),fs=require('fs'),path=require('path');const ROOT=path.join(__dirname,'..');
const immersive=fs.readFileSync(path.join(ROOT,'preview/ocean/js/ocean-immersive.js'),'utf8');const renderer=fs.readFileSync(path.join(ROOT,'preview/ocean/js/ocean-v8.js'),'utf8');const geometry=JSON.parse(fs.readFileSync(path.join(ROOT,'preview/ocean/assets/bsd/SmallFishA.json'),'utf8'));const habitat=path.join(ROOT,'preview/ocean/assets/cc0/great-barrier-reef-06.jpg');const habitatLicense=path.join(ROOT,'preview/ocean/assets/cc0/LICENSE-Great-Barrier-Reef-06.txt');
assert.ok(immersive.includes("VERSION='0.9.0'")&&immersive.includes("CACHE='11'"),'visible build is v0.9.0 with fresh cache');
assert.ok(immersive.includes('ocean-v8.js')&&immersive.includes('CinemapOceanV8'),'immersive view mounts the WebGL renderer');
assert.ok(renderer.includes("getContext('webgl2'")&&renderer.includes('SmallFishA.json')&&renderer.includes('smallfish.webp'),'foreground life remains locally vendored textured geometry');
assert.ok(renderer.includes('assets/cc0/great-barrier-reef-06.jpg'),'renderer uses the reviewed clean local reef habitat');
assert.ok(!renderer.includes('ocean-cinematic-bg.webp'),'rejected pre-baked-animal backdrop is no longer used');
assert.ok(fs.existsSync(habitat)&&fs.statSync(habitat).size>50000,'local CC0 habitat retains enough detail for iPhone presentation');
assert.ok(fs.existsSync(habitatLicense)&&fs.readFileSync(habitatLicense,'utf8').includes('CC0 1.0'),'habitat provenance and CC0 license are retained');
assert.ok(renderer.includes('tail*tail')&&renderer.includes('requestAnimationFrame')&&renderer.includes('pointermove'),'fish remain animated and scene remains explorable');
assert.ok(renderer.includes('population=clamp')&&renderer.includes('org.length'),'visible population still derives from ecosystem growth');
assert.ok(geometry.position.length>300&&geometry.normal.length===geometry.position.length&&geometry.uv.length>200,'fish mesh is real textured geometry');
assert.ok(fs.existsSync(path.join(ROOT,'preview/ocean/assets/bsd/LICENSE-WebGLSamples.txt')),'BSD fish provenance is retained');
assert.ok(!renderer.includes('http://')&&!renderer.includes('https://'),'production renderer makes no external runtime request');
assert.ok(!renderer.includes('cosmosHalo')&&!renderer.includes('fish-atlas')&&!renderer.includes('bubble'),'rejected halo/sprite/bubble treatments stay absent');
console.log('Ocean asset-led WebGL2 v0.9.0 contract tests passed');
