const fs=require('node:fs');const test=require('node:test');const assert=require('node:assert/strict');
const keys=['clownfish','sea-turtle','ocean-sunfish','giant-octopus','manta-ray','dolphin','hammerhead-shark','large-shark','dugong','minke-whale','orca','humpback-whale','whale-shark','blue-whale'];
const vectorKeys=['sea-turtle','manta-ray','dolphin','hammerhead-shark','large-shark','dugong','minke-whale','orca','humpback-whale','whale-shark','blue-whale'];
const largeVectorKeys=['manta-ray','dolphin','hammerhead-shark','large-shark','dugong','minke-whale','orca','humpback-whale','whale-shark','blue-whale'];
test('every approved milestone species has a unique atlas crop',()=>{const m=JSON.parse(fs.readFileSync('preview/ocean/real-fish/milestone-assets.json','utf8'));assert.match(m.atlas,/^optimized\/milestone-creatures-v2\.webp$/);assert.deepEqual(m.atlasSize,[400,200]);for(const key of keys){assert.ok(m.species[key],key);assert.equal(m.species[key].crop.length,4);assert.ok(m.species[key].presentationScale>0);assert.ok(m.species[key].habitat);assert.ok(m.species[key].motion);}assert.equal(m.species.seahorse,undefined);const crops=keys.map(k=>m.species[k].crop.join(','));assert.equal(new Set(crops).size,keys.length);});
test('large rigid milestone swimmers bypass the tiny raster atlas with straight scalable vector poses',()=>{const source=fs.readFileSync('preview/ocean/real-fish/milestone-atlas.js','utf8');assert.match(source,/const VECTOR_SPECIES=/);assert.match(source,/className='milestoneVectorCreature'/);assert.match(source,/dataset\.pose='straight'/);for(const key of vectorKeys){assert.ok(source.includes(key),key);}});
test('large milestone vectors use lightweight species-specific body lighting instead of flat single-color bodies',()=>{const source=fs.readFileSync('preview/ocean/real-fish/milestone-atlas.js','utf8');assert.match(source,/const LIGHTING_PROFILES=/);assert.match(source,/createElementNS\(SVG_NS,'linearGradient'\)/);assert.match(source,/dataset\.renderQuality='lit-vector-v1'/);assert.match(source,/primary\.setAttribute\('fill','url\(#'\+gradientId\+'\)'\)/);for(const key of largeVectorKeys){assert.ok(source.includes(`'${key}':{light:`),key);}assert.doesNotMatch(source,/feGaussianBlur|feDropShadow|drop-shadow\(/);});
test('milestone catalog never uses data URIs or generic fish substitutions',()=>{const text=fs.readFileSync('preview/ocean/real-fish/milestone-assets.json','utf8');assert.doesNotMatch(text,/data:image/i);assert.doesNotMatch(text,/fish-real|species-stingray/);});
test('milestone atlas file is a committed WebP rather than an invalid transferred binary',()=>{const m=JSON.parse(fs.readFileSync('preview/ocean/real-fish/milestone-assets.json','utf8')),bytes=fs.readFileSync('preview/ocean/real-fish/'+m.atlas);assert.equal(bytes.subarray(0,4).toString('ascii'),'RIFF');assert.equal(bytes.subarray(8,12).toString('ascii'),'WEBP');});
