const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const store = new Map();
const ctx = {localStorage: {getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}, Date};
vm.runInNewContext(fs.readFileSync('js/viewing-records.js','utf8'),ctx);
const r=ctx.CinemapRecords, a={id:346,title:'七人の侍',year:1954,genres:['ドラマ']};
assert.equal(r.get(a),null);
assert.equal(r.toggleResonated(a),false,'unwatched films cannot resonate');
assert.equal(r.rate(a,4.2),true,'one rating gesture creates a watched record');
assert.equal(r.get(a).watched,true);
assert.equal(r.get(a).rating,4.2);
const firstRecordedAt=r.get(a).recordedAt;
assert.match(firstRecordedAt,/^\d{4}-\d\d-/);
assert.equal(r.get(a).resonated,false);
for(const score of [0.1,1.7,2.5,3,3.5,4,4.5,4.9,5]) assert.equal(r.rate(a,score),true,'tenths across the range are accepted');
assert.equal(r.get(a).rating,5);
assert.equal(r.get(a).recordedAt,firstRecordedAt,'rating changes keep the first record date');
assert.equal(r.rate(a,5.1),false);
assert.equal(r.rate(a,4.25),false,'scores use exactly one decimal place');
assert.equal(r.rate(a,0),true,'zero clears the rating and watched record');
assert.equal(r.get(a),null);
assert.equal(r.rate(a,3.9),true);
assert.match(r.get(a).updatedAt,/^\d{4}-\d\d-/);
assert.equal(r.toggleResonated(a),true);
assert.equal(r.get(a).resonated,true);
assert.equal(Object.keys(r.read()).length,1,'one record per film');
assert.equal(r.get({tmdbId:346}).resonated,true);
assert.equal(r.toggleWatched(a),true);
assert.equal(r.get(a),null,'second tap unsets record');
assert.equal(r.toggleResonated(a),false);
assert.equal(r.setRating(a,5),true,'setting a score records the film');
assert.equal(r.get(a).watched,true);
r.rate(a,0);
r.setWatched(a,true);
const persisted=JSON.parse(store.values().next().value);
assert.equal(persisted['346'].title,'七人の侍');
const restored={localStorage:ctx.localStorage,Date};vm.runInNewContext(fs.readFileSync('js/viewing-records.js','utf8'),restored);
assert.equal(restored.CinemapRecords.get({id:346}).watched,true,'new page context restores saved record');
r.clear(); assert.equal(Object.keys(r.read()).length,0);
assert.equal(r.setWatched({id:'invalid'},true),false);
console.log('record state transitions, persistence, reset and ID validation passed');
