(function(root){'use strict';
let catalog=null;
function loadCatalog(){if(catalog)return Promise.resolve(catalog);return fetch('milestone-assets.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('milestone catalog '+r.status);return r.json()}).then(data=>(catalog=data));}
function decorate(wrap,key,spec){wrap.className='milestoneAtlasCreature';wrap.dataset.milestoneKey=key;wrap.dataset.motion=spec.motion||'';wrap.dataset.habitat=spec.habitat||'';wrap.dataset.presentationScale=String(spec.presentationScale||1);wrap.dataset.pose=spec.bodyPose||'natural-cruise';return wrap;}
function createDirectCreature(key,spec){const wrap=decorate(document.createElement('span'),key,spec),img=document.createElement('img');Object.assign(wrap.style,{display:'block',position:'relative',overflow:'visible',aspectRatio:'2 / 1',background:'transparent'});img.src=spec.asset;img.alt='';img.loading='eager';img.decoding='async';Object.assign(img.style,{display:'block',width:'100%',height:'100%',objectFit:'contain',pointerEvents:'none',userSelect:'none'});wrap.appendChild(img);return wrap;}
function createAssetCropCreature(key,spec){if(!Array.isArray(spec.assetCrop))return null;const [x,y,w,h]=spec.assetCrop,sourceAspect=Math.max(.1,Number(spec.assetAspect)||1.5);const wrap=decorate(document.createElement('span'),key,spec),img=document.createElement('img');Object.assign(wrap.style,{display:'block',position:'relative',overflow:'hidden',aspectRatio:String(sourceAspect*w/h),background:'transparent'});img.src=spec.asset;img.alt='';img.loading='eager';img.decoding='async';Object.assign(img.style,{position:'absolute',width:(10000/w)+'%',height:'auto',maxWidth:'none',left:(-100*x/w)+'%',top:(-100*y/h)+'%',pointerEvents:'none',userSelect:'none'});wrap.appendChild(img);return wrap;}
function createAtlasCreature(key,spec,manifest){if(!Array.isArray(spec.crop))return null;const [x,y,w,h]=spec.crop;const wrap=decorate(document.createElement('span'),key,spec),img=document.createElement('img');Object.assign(wrap.style,{display:'block',position:'relative',overflow:'hidden',aspectRatio:String((2*w)/h),background:'transparent'});img.src=manifest.atlas;img.alt='';img.loading='eager';img.decoding='sync';Object.assign(img.style,{position:'absolute',width:(10000/w)+'%',height:'auto',maxWidth:'none',left:(-100*x/w)+'%',top:(-100*y/h)+'%',pointerEvents:'none',userSelect:'none'});wrap.appendChild(img);return wrap;}
function createCreature(key,manifest=catalog){const spec=manifest?.species?.[key];if(!spec)return null;if(spec.asset&&Array.isArray(spec.assetCrop))return createAssetCropCreature(key,spec);if(spec.asset)return createDirectCreature(key,spec);return createAtlasCreature(key,spec,manifest);}
root.CinemapOceanMilestoneAtlas={loadCatalog,createCreature,get catalog(){return catalog}};
})(window);
