(function(root){'use strict';
const VERSION='0.9.0',ASSET='assets/bsd/',HABITAT='assets/cc0/great-barrier-reef-06.jpg';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function m4(){return new Float32Array(16)}function ident(o){o.fill(0);o[0]=o[5]=o[10]=o[15]=1;return o}
function mul(out,a,b){const r=m4();for(let c=0;c<4;c++)for(let row=0;row<4;row++)r[c*4+row]=a[row]*b[c*4]+a[4+row]*b[c*4+1]+a[8+row]*b[c*4+2]+a[12+row]*b[c*4+3];out.set(r);return out}
function perspective(out,fovy,aspect,near,far){const f=1/Math.tan(fovy/2);out.fill(0);out[0]=f/aspect;out[5]=f;out[10]=(far+near)/(near-far);out[11]=-1;out[14]=2*far*near/(near-far);return out}
function lookAt(out,e,t,u){let zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],l=Math.hypot(zx,zy,zz);zx/=l;zy/=l;zz/=l;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx;l=Math.hypot(xx,xy,xz);xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;out.set([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*e[0]+xy*e[1]+xz*e[2]),-(yx*e[0]+yy*e[1]+yz*e[2]),-(zx*e[0]+zy*e[1]+zz*e[2]),1]);return out}
function model(out,x,y,z,s,dir,roll){ident(out);const c=Math.cos(dir),sn=Math.sin(dir),cr=Math.cos(roll),sr=Math.sin(roll);out[0]=c*s;out[1]=sr*sn*s;out[2]=-cr*sn*s;out[5]=cr*s;out[6]=sr*s;out[8]=sn*s;out[9]=-sr*c*s;out[10]=cr*c*s;out[12]=x;out[13]=y;out[14]=z;return out}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}function program(gl,v,f){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function rnd(s,n){let x=hash(s+'|'+n);x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967295}
const VS=`#version 300 es\nprecision highp float;layout(location=0)in vec3 p;layout(location=1)in vec3 n;layout(location=2)in vec2 uv;uniform mat4 vp,m;uniform float time,phase,bend;out vec3 N;out vec2 UV;out float D;void main(){vec3 q=p;float tail=clamp((-q.z-.08)*1.45,0.,1.);q.x+=sin(time*3.0+phase+q.z*1.8)*tail*tail*bend;vec4 w=m*vec4(q,1);N=normalize(mat3(m)*n);UV=uv;D=-w.z;gl_Position=vp*w;}`;
const FS=`#version 300 es\nprecision highp float;in vec3 N;in vec2 UV;in float D;uniform sampler2D tex;uniform vec3 tint;out vec4 o;void main(){vec4 t=texture(tex,UV);if(t.a<.08)discard;float l=.42+.58*max(dot(normalize(N),normalize(vec3(-.22,.82,.52))),0.);vec3 c=t.rgb*tint*l;float fog=clamp((D-10.)/34.,0.,.72);c=mix(c,vec3(.025,.19,.22),fog);o=vec4(c,t.a*.94);}`;
function mesh(gl,g){const vao=gl.createVertexArray();gl.bindVertexArray(vao);for(const [loc,d,size] of [[0,g.position,3],[1,g.normal,3],[2,g.uv,2]]){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(d),gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0)}const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(g.indices),gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:g.indices.length}}
function image(src){return new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=src})}
async function mount(viewport,ecosystem){viewport.innerHTML='';viewport.style.background='#03151d';const bg=document.createElement('div');bg.className='oceanV9Habitat';bg.style.cssText=`position:absolute;inset:-7%;background:url(${HABITAT}) 50% 47%/cover no-repeat;transform:scale(1.10);filter:saturate(.78) contrast(1.07) brightness(.70);will-change:transform;transition:transform .16s ease-out`;const water=document.createElement('div');water.className='oceanV9Water';water.style.cssText='position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse at 48% -8%,rgba(185,244,238,.16),transparent 45%),linear-gradient(180deg,rgba(0,24,34,.01),rgba(0,17,25,.24));box-shadow:inset 0 0 110px 20px rgba(0,10,18,.40)';const rays=document.createElement('div');rays.className='oceanV9Rays';rays.style.cssText='position:absolute;inset:-12%;pointer-events:none;opacity:.16;background:linear-gradient(104deg,transparent 22%,rgba(190,244,237,.16) 34%,transparent 43%,rgba(170,235,231,.10) 51%,transparent 62%);filter:blur(8px);animation:oceanV9Drift 13s ease-in-out infinite alternate';const canvas=document.createElement('canvas');canvas.style.cssText='position:absolute;inset:0;width:100%;height:100%;display:block;touch-action:none';viewport.append(bg,water,rays,canvas);if(!document.getElementById('ocean-v9-style')){const s=document.createElement('style');s.id='ocean-v9-style';s.textContent='@keyframes oceanV9Drift{from{transform:translate3d(-2%,-1%,0) skewX(-2deg)}to{transform:translate3d(3%,1%,0) skewX(2deg)}}';document.head.appendChild(s)}
const gl=canvas.getContext('webgl2',{alpha:true,antialias:true,premultipliedAlpha:false,powerPreference:'high-performance'});if(!gl)throw Error('WebGL2 unavailable');const [g,im]=await Promise.all([fetch(ASSET+'SmallFishA.json').then(r=>r.json()),image(ASSET+'smallfish.webp')]);const p=program(gl,VS,FS),me=mesh(gl,g),tx=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tx);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,im);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);
const org=[...(ecosystem?.organisms||[])],population=clamp(Math.round(5+(org.length||8)*.16),6,14),fish=[];for(let i=0;i<population;i++){const o=org[i%Math.max(1,org.length)]||{id:'ambient'+i},seed=(o.film?.id||o.id||'ambient')+'-'+i,z=-8-rnd(seed,'z')*25,x=(rnd(seed,'x')-.5)*34,y=-1+rnd(seed,'y')*10,hero=!!o.hero,s=(.56+rnd(seed,'s')*.72)*(hero?1.42:1),dir=rnd(seed,'d')>.5?Math.PI/2:-Math.PI/2;fish.push({x,y,z,s,dir,phase:rnd(seed,'p')*6.28,speed:.14+rnd(seed,'v')*.34,tint:[.80+rnd(seed,'r')*.13,.84+rnd(seed,'g')*.11,.86+rnd(seed,'b')*.10]})}
const cam={x:0,y:1,z:17,zoom:.72},ptr=new Map(),u={vp:gl.getUniformLocation(p,'vp'),m:gl.getUniformLocation(p,'m'),time:gl.getUniformLocation(p,'time'),phase:gl.getUniformLocation(p,'phase'),bend:gl.getUniformLocation(p,'bend'),tint:gl.getUniformLocation(p,'tint')};let raf=0,dead=false,last=performance.now();
function resize(){const r=viewport.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);return{w,h}}
function draw(ms){if(dead)return;const t=ms/1000,dt=Math.min(.05,(ms-last)/1000);last=ms;const {w,h}=resize();gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const pr=perspective(m4(),Math.PI/(2.62*cam.zoom),w/h,.1,100),vw=lookAt(m4(),[cam.x,cam.y,cam.z],[cam.x*.72,cam.y-.6,-16],[0,1,0]),vp=mul(m4(),pr,vw);gl.useProgram(p);gl.uniformMatrix4fv(u.vp,false,vp);gl.uniform1f(u.time,t);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tx);gl.bindVertexArray(me.vao);for(const f of fish){f.x+=(f.dir>0?1:-1)*f.speed*dt;if(f.x>19)f.x=-19;if(f.x<-19)f.x=19;const mm=model(m4(),f.x,f.y,f.z,f.s,f.dir,Math.sin(t*.20+f.phase)*.025);gl.uniformMatrix4fv(u.m,false,mm);gl.uniform1f(u.phase,f.phase);gl.uniform1f(u.bend,.13+.07*f.speed);gl.uniform3fv(u.tint,f.tint);gl.drawElements(gl.TRIANGLES,me.count,gl.UNSIGNED_SHORT,0)}raf=requestAnimationFrame(draw)}
function pt(e){const r=viewport.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}viewport.addEventListener('pointerdown',e=>{viewport.setPointerCapture?.(e.pointerId);ptr.set(e.pointerId,pt(e))});viewport.addEventListener('pointermove',e=>{const a=ptr.get(e.pointerId);if(!a)return;const b=pt(e);ptr.set(e.pointerId,b);if(ptr.size===1){cam.x=clamp(cam.x-(b.x-a.x)*.055,-16,16);cam.y=clamp(cam.y+(b.y-a.y)*.035,-4,8);bg.style.transform=`translate3d(${cam.x*-.62}px,${cam.y*.48}px,0) scale(1.12)`}else if(ptr.size===2){const q=[...ptr.values()],d=Math.hypot(q[0].x-q[1].x,q[0].y-q[1].y);cam.zoom=clamp(.56+d/720,.62,1.18)}});const end=e=>ptr.delete(e.pointerId);viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);raf=requestAnimationFrame(draw);return{version:VERSION,fallback:false,reset(){cam.x=0;cam.y=1;cam.zoom=.72;bg.style.transform='scale(1.10)'},destroy(){dead=true;cancelAnimationFrame(raf)}}}
root.CinemapOceanV9={VERSION,mount};})(window);
