(function(root){'use strict';
const VERSION='0.7.0',ASSET='assets/bsd/';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function mat4(){return new Float32Array(16)}
function ident(o){o.fill(0);o[0]=o[5]=o[10]=o[15]=1;return o}
function mul(out,a,b){const r=mat4();for(let c=0;c<4;c++)for(let row=0;row<4;row++)r[c*4+row]=a[row]*b[c*4]+a[4+row]*b[c*4+1]+a[8+row]*b[c*4+2]+a[12+row]*b[c*4+3];out.set(r);return out}
function perspective(out,fovy,aspect,near,far){const f=1/Math.tan(fovy/2);out.fill(0);out[0]=f/aspect;out[5]=f;out[10]=(far+near)/(near-far);out[11]=-1;out[14]=2*far*near/(near-far);return out}
function lookAt(out,eye,target,up){let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],l=Math.hypot(zx,zy,zz);zx/=l;zy/=l;zz/=l;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx;l=Math.hypot(xx,xy,xz);xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;out.set([xx,yx,zx,0,xy,yy,zy,0,xz,yz,zz,0,-(xx*eye[0]+xy*eye[1]+xz*eye[2]),-(yx*eye[0]+yy*eye[1]+yz*eye[2]),-(zx*eye[0]+zy*eye[1]+zz*eye[2]),1]);return out}
function model(out,x,y,z,s,dir,roll=0){ident(out);const c=Math.cos(dir),sn=Math.sin(dir),cr=Math.cos(roll),sr=Math.sin(roll);out[0]=c*s;out[1]=sr*sn*s;out[2]=-cr*sn*s;out[4]=0;out[5]=cr*s;out[6]=sr*s;out[8]=sn*s;out[9]=-sr*c*s;out[10]=cr*c*s;out[12]=x;out[13]=y;out[14]=z;return out}
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rnd(seed,n){let x=hash(seed+'|'+n);x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967295}
const VS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aNormal;layout(location=2)in vec2 aUV;uniform mat4 uVP,uModel;uniform float uTime,uPhase,uBend;out vec3 vN;out vec2 vUV;out float vDepth;void main(){vec3 p=aPos;float tail=clamp((-p.z-.12)*1.35,0.0,1.0);p.x+=sin(uTime*3.1+uPhase+p.z*1.7)*tail*tail*uBend;vec4 w=uModel*vec4(p,1.0);vN=normalize(mat3(uModel)*aNormal);vUV=aUV;vDepth=-w.z;gl_Position=uVP*w;}`;
const FS=`#version 300 es
precision highp float;in vec3 vN;in vec2 vUV;in float vDepth;uniform sampler2D uTex;uniform vec3 uTint;out vec4 outColor;void main(){vec4 tex=texture(uTex,vUV);vec3 n=normalize(vN);vec3 light=normalize(vec3(-.35,.8,.45));float nd=.28+.72*max(dot(n,light),0.0);vec3 c=tex.rgb*uTint*nd;float fog=clamp((vDepth-5.0)/34.0,0.0,.82);c=mix(c,vec3(.025,.20,.27),fog);outColor=vec4(c,1.0);}`;
const BGVS=`#version 300 es
precision highp float;const vec2 P[3]=vec2[3](vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.));out vec2 uv;void main(){gl_Position=vec4(P[gl_VertexID],0,1);uv=P[gl_VertexID]*.5+.5;}`;
const BGFS=`#version 300 es
precision highp float;in vec2 uv;uniform float t;uniform vec2 res;out vec4 o;
float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+1.),f.x),f.y);}float seg(vec2 p,vec2 a,vec2 b){vec2 pa=p-a,ba=b-a;float q=clamp(dot(pa,ba)/dot(ba,ba),0.,1.);return length(pa-ba*q);}
void main(){vec2 p=uv;float d=pow(p.y,1.25);vec3 top=vec3(.035,.39,.50),bot=vec3(.006,.055,.095);vec3 c=mix(bot,top,d);float rays=0.;for(int i=0;i<6;i++){float x=.08+float(i)*.19+sin(t*.06+float(i))*0.04;float beam=1.-smoothstep(.015,.12,abs(p.x-x-(1.-p.y)*(.10+float(i)*.014)));rays+=beam*pow(p.y,1.9);}c+=vec3(.08,.23,.21)*rays*.30;float ca=sin((p.x*19.+n(p*8.+t*.04)*4.)+t*.22)*sin((p.y*25.-t*.16)+n(p*10.)*3.);c+=vec3(.05,.13,.11)*max(ca,0.)*.09*pow(p.y,3.);float floorY=.16+.028*sin(p.x*11.)+.018*sin(p.x*29.+1.4);float floorMask=1.-smoothstep(floorY-.015,floorY+.025,p.y);c=mix(c,vec3(.025,.105,.105),floorMask*.92);for(int i=0;i<11;i++){float fi=float(i),x=.035+fi*.096+h(vec2(fi,4.))*0.035,height=.10+h(vec2(fi,7.))*.20;float sway=sin(t*.34+fi*1.7)*.018;vec2 a=vec2(x,floorY),b=vec2(x+sway,floorY+height);float k=1.-smoothstep(.006,.014,seg(p,a,b));c=mix(c,vec3(.025,.18+.035*h(vec2(fi)),.13),k*.72);for(int j=1;j<4;j++){float fj=float(j),yy=floorY+height*fj*.22;vec2 aa=vec2(x+sway*fj*.22,yy),bb=aa+vec2((mod(fi+fj,2.)>.5?1.:-1.)*.035,.045);float leaf=1.-smoothstep(.004,.012,seg(p,aa,bb));c=mix(c,vec3(.035,.22,.16),leaf*.58);}}for(int i=0;i<7;i++){float fi=float(i),x=.10+fi*.135+h(vec2(fi,12.))*.04,y=floorY+.012,ht=.045+h(vec2(fi,13.))*.07;float trunk=1.-smoothstep(.004,.011,seg(p,vec2(x,y),vec2(x,y+ht)));float b1=1.-smoothstep(.003,.009,seg(p,vec2(x,y+ht*.45),vec2(x-.035,y+ht*.78)));float b2=1.-smoothstep(.003,.009,seg(p,vec2(x,y+ht*.58),vec2(x+.04,y+ht*.88)));float coral=max(trunk,max(b1,b2));c=mix(c,vec3(.35,.18,.12),coral*.65);}float dust=step(.996,n(p*vec2(210.,150.)+vec2(t*.015,-t*.025)));c+=dust*vec3(.12,.20,.18)*.22;float grain=n(p*vec2(120.,80.)+t*.02);c+=(grain-.5)*.016;float vign=smoothstep(.86,.24,distance(p,vec2(.5,.52)));c*=.70+.30*vign;o=vec4(c,1);}`
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function makeMesh(gl,g){const vao=gl.createVertexArray();gl.bindVertexArray(vao);for(const [loc,data,size] of [[0,g.position,3],[1,g.normal,3],[2,g.uv,2]]){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0)}const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(g.indices),gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:g.indices.length}}
async function mount(viewport,ecosystem,options={}){viewport.innerHTML='';const canvas=document.createElement('canvas');canvas.className='oceanCinematicCanvas';canvas.style.cssText='display:block;width:100%;height:100%;touch-action:none';viewport.appendChild(canvas);const gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl)throw new Error('WebGL2 unavailable');const [geom,img]=await Promise.all([fetch(ASSET+'SmallFishA.json').then(r=>r.json()),loadImage(ASSET+'smallfish.webp')]);const fishP=program(gl,VS,FS),bgP=program(gl,BGVS,BGFS),mesh=makeMesh(gl,geom);const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
const org=[...(ecosystem?.organisms||[])],count=clamp(org.length||18,12,42);const fish=[];for(let i=0;i<count;i++){const o=org[i]||{id:'ambient'+i};const seed=o.film?.id||o.id||i,z=-6-rnd(seed,'z')*31,x=(rnd(seed,'x')-.5)*26,y=-3+rnd(seed,'y')*12,s=(.55+rnd(seed,'s')*1.25)*(o.hero?1.7:1),dir=rnd(seed,'d')>.5?Math.PI/2:-Math.PI/2;fish.push({o,x,y,z,s,dir,phase:rnd(seed,'p')*6.28,speed:.25+rnd(seed,'v')*.55,tint:[.72+rnd(seed,'r')*.25,.78+rnd(seed,'g')*.2,.76+rnd(seed,'b')*.2]})}
const camera={x:0,y:1,z:13,zoom:1},ptr=new Map();let raf=0,dead=false,last=performance.now();const u={vp:gl.getUniformLocation(fishP,'uVP'),model:gl.getUniformLocation(fishP,'uModel'),time:gl.getUniformLocation(fishP,'uTime'),phase:gl.getUniformLocation(fishP,'uPhase'),bend:gl.getUniformLocation(fishP,'uBend'),tint:gl.getUniformLocation(fishP,'uTint')};
function resize(){const r=viewport.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.round(r.width*d),h=Math.round(r.height*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);return{w,h,d}}
function draw(ms){if(dead)return;const t=ms/1000,dt=Math.min(.05,(ms-last)/1000);last=ms;const {w,h}=resize();gl.disable(gl.DEPTH_TEST);gl.useProgram(bgP);gl.uniform1f(gl.getUniformLocation(bgP,'t'),t);gl.uniform2f(gl.getUniformLocation(bgP,'res'),w,h);gl.drawArrays(gl.TRIANGLES,0,3);gl.enable(gl.DEPTH_TEST);gl.clear(gl.DEPTH_BUFFER_BIT);const proj=perspective(mat4(),Math.PI/(3.2*camera.zoom),w/h,.1,100),view=lookAt(mat4(),[camera.x,camera.y,camera.z],[camera.x,camera.y-1,-16],[0,1,0]),vp=mul(mat4(),proj,view);gl.useProgram(fishP);gl.uniformMatrix4fv(u.vp,false,vp);gl.uniform1f(u.time,t);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.bindVertexArray(mesh.vao);for(const f of fish){f.x+=(f.dir>0?1:-1)*f.speed*dt;if(f.x>17)f.x=-17;if(f.x<-17)f.x=17;const m=model(mat4(),f.x,f.y,f.z,f.s,f.dir,Math.sin(t*.25+f.phase)*.04);gl.uniformMatrix4fv(u.model,false,m);gl.uniform1f(u.phase,f.phase);gl.uniform1f(u.bend,.18+.08*f.speed);gl.uniform3fv(u.tint,f.tint);gl.drawElements(gl.TRIANGLES,mesh.count,gl.UNSIGNED_SHORT,0)}gl.bindVertexArray(null);raf=requestAnimationFrame(draw)}
function point(e){const r=viewport.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
viewport.addEventListener('pointerdown',e=>{viewport.setPointerCapture?.(e.pointerId);ptr.set(e.pointerId,point(e))});viewport.addEventListener('pointermove',e=>{const p0=ptr.get(e.pointerId);if(!p0)return;const p=point(e);ptr.set(e.pointerId,p);if(ptr.size===1){camera.x=clamp(camera.x-(p.x-p0.x)*.035,-11,11);camera.y=clamp(camera.y+(p.y-p0.y)*.025,-2,6)}else if(ptr.size===2){const a=[...ptr.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);camera.zoom=clamp(.7+d/520,.72,1.35)}});const end=e=>ptr.delete(e.pointerId);viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);viewport.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=clamp(camera.zoom*(e.deltaY>0?.92:1.08),.72,1.35)},{passive:false});raf=requestAnimationFrame(draw);return{fallback:false,version:VERSION,reset(){camera.x=0;camera.y=1;camera.zoom=1},destroy(){dead=true;cancelAnimationFrame(raf)}}}
root.CinemapOcean3D={VERSION,mount};
})(window);
