(function(root){'use strict';
let previousSignature=null;
function records(){return root.CinemapRecords?.read?.()||{}}
function values(){return Object.values(records()).filter(r=>r&&r.watched)}
function text(id,value){const el=document.getElementById(id);if(el)el.textContent=value}
function escapeHtml(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function stage(n){const stages=[[0,'静かな海'],[5,'最初の生命'],[10,'小さな群れ'],[20,'育ち始めたリーフ'],[35,'豊かな生態系'],[55,'成熟した海'],[80,'あなたの大海原']];let current=stages[0],next=null;for(const item of stages){if(n>=item[0])current=item;else{next=item;break}}return{current,next}}
function renderList(items){const host=document.getElementById('entries');if(!host)return;host.innerHTML=items.length?items.map(r=>'<div class="entry"><div class="name"><strong>'+escapeHtml(r.title||'記録した映画')+'</strong><small>'+(r.year||'')+(r.rating?' · '+Number(r.rating).toFixed(1):'')+'</small></div></div>').join(''):'<p class="empty">まだ記録はありません。</p>'}
function ecologyFor(items){try{return root.CinemapOceanModel?.ecosystem?.(records(),items)||null}catch(err){console.error('[Ocean ecology]',err);return null}}
function showGrowth(items,ecology){const host=document.getElementById('speciesCollection');if(!host)return;const n=items.length,g=stage(n),last=items.at(-1),species=last&&root.CinemapOceanModel?.speciesFor?.(last);const discovered=ecology?.discovered?.length||0;const next=g.next?`あと${g.next[0]-n}本で「${g.next[1]}」`:'海は最終成長段階です';host.innerHTML=n?'<div class="speciesTile growthCard"><small>いまの海</small><strong>'+escapeHtml(g.current[1])+'</strong><span>'+discovered+'種類の生命 · '+escapeHtml(next)+'</span></div>'+(species?'<div class="speciesTile latestLife"><small>最新の生命</small><strong>'+escapeHtml(species.name)+'</strong><span>'+escapeHtml(last.title||'新しい映画')+'から誕生</span></div>':''):'<p class="empty">映画を記録すると、最初の生命が現れます。</p>';
const signature=n+':'+discovered+':'+(species?.id||'');if(previousSignature!==null&&signature!==previousSignature&&last){const toast=document.getElementById('speciesToast');if(toast){toast.innerHTML='<strong>海が育ちました</strong><span>'+(species?'「'+escapeHtml(species.name)+'」が誕生。':'新しい生命が加わりました。')+' '+escapeHtml(next)+'</span>';toast.hidden=false;clearTimeout(showGrowth.timer);showGrowth.timer=setTimeout(()=>{toast.hidden=true},4200)}}previousSignature=signature}
function render(){const items=values(),dashboard=document.getElementById('dashboard'),onboarding=document.getElementById('onboarding');if(dashboard)dashboard.hidden=false;if(onboarding)onboarding.hidden=true;const ecology=ecologyFor(items);text('dashboardCount',items.length+'本記録済み');text('watchedCount',items.length);text('resonatedCount',items.filter(r=>Number.isFinite(Number(r.rating))).length);text('speciesCount',ecology?'· '+ecology.discovered.length+'種類':'');renderList(items);showGrowth(items,ecology);const trends=document.getElementById('trends');if(trends)trends.innerHTML=items.length?'<span class="chip">生命 '+(ecology?.discovered?.length||0)+'種類</span><span class="chip">珊瑚 '+(ecology?.environment?.coral||0)+'</span><span class="chip">海藻 '+(ecology?.environment?.seaweed||0)+'</span><span class="chip">群れ '+(ecology?.environment?.ambientSchools||0)+'</span>':'<span class="chip">最初の映画を待っています</span>';const coverage=document.getElementById('coverage');if(coverage)coverage.textContent=items.length+'作品を記録 · 海の豊かさ '+Math.round((ecology?.environment?.richness||0)*100)+'%';const missing=document.getElementById('missing');if(missing)missing.innerHTML='';try{root.CinemapOceanImmersive?.mount?.(items,records())}catch(err){console.error('[Ocean dashboard]',err);const e=document.getElementById('loadError');if(e)e.textContent='3D表示に問題がありますが、記録データは引き続き確認できます。'}}
function boot(){try{render();root.CinemapRecords?.subscribe?.(render)}catch(err){console.error('[Ocean boot]',err);const dashboard=document.getElementById('dashboard');if(dashboard)dashboard.hidden=false;const e=document.getElementById('loadError');if(e)e.textContent='海の一部を読み込めませんでした。ページ本文はそのまま利用できます。'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window);
