(function(root){
'use strict';
const VERSION='0.5.0';
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0]);}
function viewMatrix(camera){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,-camera.x,-camera.y,-camera.distance,1]);}
function modelMatrix(x,y,z,sx,sy,sz,yaw){const c=Math.cos(yaw||0),s=Math.sin(yaw||0);return new Float32Array([c*sx,0,-s*sx,0,0,sy,0,0,s*sz,0,c*sz,0,x,y,z,1]);}
function hsl(h,s,l){h=((h%360)+360)%360/360;const hue=(p,q,t)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};const q=l<.5?l*(1+s):l+s-l*s,p=2*l-q;return [hue(p,q,h+1/3),hue(p,q,h),hue(p,q,h-1/3)];}
function injectStyle(){if(document.getElementById('ocean-v5-style'))return;const s=document.createElement('style');s.id='ocean-v5-style';s.textContent=`.oceanV5Viewport{position:relative;width:100%;height:min(76svh,820px);min-height:560px;overflow:hidden;touch-action:none;background:linear-gradient(180deg,#07324a 0%,#06263a 38%,#041a2b 70%,#020d18 100%);border-radius:0 0 18px 18px}.oceanV5Canvas{display:block;width:100%;height:100%;touch-action:none}.oceanV5Fallback{position:absolute;inset:0;display:grid;place-items:end center;padding:28px;text-align:center;background:linear-gradient(180deg,#0a3b55,#041b2a 60%,#020d17);color:#d9edf0}.oceanV5Fallback strong{display:block;font:24px Georgia,serif;margin-bottom:8px}.oceanV5Fallback p{max-width:440px;font-size:12px;line-height:1.7;color:#a9c9d0}.oceanV5Fallback:before{content:"";position:absolute;left:5%;right:5%;bottom:18%;height:24%;background:linear-gradient(160deg,transparent 0 12%,#123c3b 13% 25%,transparent 26% 34%,#0d3336 35% 55%,transparent 56% 63%,#17443e 64% 82%,transparent 83%);opacity:.8;filter:blur(1px)}@media(max-width:600px){.oceanV5Viewport{height:68svh;min-height:520px}}`;document.head.appendChild(s);}
function makeMesh(gl,data){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const p=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,p);gl.bufferData(gl.ARRAY_BUFFER,data.positions,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);const a=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,a);gl.bufferData(gl.ARRAY_BUFFER,data.parts,gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,1,gl.FLOAT,false,0,0);gl.bindVertexArray(null);return {vao,count:data.count};}
function showFallback(viewport,message){viewport.innerHTML=`<div class="oceanV5Fallback" role="img" aria-label="海中生態系の互換表示"><div><strong>あなたの海はここにあります</strong><p>${message||'この端末では3D表示を開始できませんでした。鑑賞記録はそのまま保存されています。'}</p></div></div>`;return {fallback:true,version:VERSION,destroy(){},reset(){}};}
function mount(viewport,ecosystem,options){
  options=options||{};injectStyle();viewport.classList.add('oceanV5Viewport');viewport.innerHTML='';const canvas=document.createElement('canvas');canvas.className='oceanV5Canvas';canvas.setAttribute('aria-label','映画の記録から育つ3D海洋生態系');viewport.appendChild(canvas);
  let gl;try{gl=canvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'high-performance'});}catch(_e){}if(!gl)return showFallback(viewport,'WebGL2に対応したブラウザでは、ここにリアルタイムの海中生態系が表示されます。');
  let program;try{program=root.CinemapOceanShaders.createProgram(gl);}catch(e){console.error(e);return showFallback(viewport,'3D描画の初期化に失敗しました。記録データには影響ありません。');}
  const scene=root.CinemapOceanScene.buildRenderScene(ecosystem),geo=root.CinemapOceanGeometry;const meshes={fish:makeMesh(gl,geo.fish()),rock:makeMesh(gl,geo.rock()),blade:makeMesh(gl,geo.blade()),seabed:makeMesh(gl,geo.seabed()),particle:makeMesh(gl,geo.particle())};
  let selected=null;const camera=root.CinemapOceanCamera.createCameraController(viewport,{onTap:(e)=>{const r=viewport.getBoundingClientRect(),nx=(e.clientX-r.left)/r.width-.5,ny=.5-(e.clientY-r.top)/r.height,cs=camera.getState();let best=null,score=.18;for(const f of scene.fish){const sx=(f.x-cs.x)/scene.world.width,sy=(f.y-cs.y)/12,d=Math.hypot(sx-nx,sy-ny);if(d<score){score=d;best=f;}}selected=best;if(best&&options.onSelect)options.onSelect(best);}});
  const loc={projection:gl.getUniformLocation(program,'uProjection'),view:gl.getUniformLocation(program,'uView'),model:gl.getUniformLocation(program,'uModel'),time:gl.getUniformLocation(program,'uTime'),phase:gl.getUniformLocation(program,'uPhase'),tail:gl.getUniformLocation(program,'uTail'),sway:gl.getUniformLocation(program,'uSway'),color:gl.getUniformLocation(program,'uColor'),fog:gl.getUniformLocation(program,'uFogColor'),alpha:gl.getUniformLocation(program,'uAlpha'),light:gl.getUniformLocation(program,'uLight')};
  gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(.012,.055,.09,1);let raf=0,last=performance.now(),lost=false;
  function resize(){const dpr=Math.min(1.5,root.devicePixelRatio||1),w=Math.max(1,Math.round(viewport.clientWidth*dpr)),h=Math.max(1,Math.round(viewport.clientHeight*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);return w/h;}
  function draw(mesh,model,color,alpha,time,phase,tail,sway){gl.bindVertexArray(mesh.vao);gl.uniformMatrix4fv(loc.model,false,model);gl.uniform3fv(loc.color,color);gl.uniform1f(loc.alpha,alpha);gl.uniform1f(loc.time,time);gl.uniform1f(loc.phase,phase||0);gl.uniform1f(loc.tail,tail||0);gl.uniform1f(loc.sway,sway||0);gl.drawArrays(gl.TRIANGLES,0,mesh.count);}
  function frame(now){if(lost)return;const dt=Math.min(.04,(now-last)/1000);last=now;const t=now/1000,aspect=resize(),cam=camera.update();gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix4fv(loc.projection,false,perspective(Math.PI/3.15,aspect,.1,140));gl.uniformMatrix4fv(loc.view,false,viewMatrix(cam));gl.uniform3fv(loc.fog,new Float32Array([.018,.105,.16]));gl.uniform1f(loc.light,scene.light);
    draw(meshes.seabed,modelMatrix(0,0,0,1,1,1,0),[.055,.18,.17],1,t,0,0,0);
    for(const h of scene.habitat){const isGrass=h.type==='grass'||h.type==='coral',m=isGrass?meshes.blade:meshes.rock,c=h.type==='coral'?hsl(h.hue,.42,.34):h.type==='grass'?[.08,.29,.23]:[.12,.2,.2];draw(m,modelMatrix(h.x,h.y,h.z,h.scale*(isGrass ? .7 : 1),h.scale*(isGrass ? 1.35 : 1),h.scale,h.phase),c,.94,t,h.phase,0,isGrass ? .7 : 0);}
    for(const p of scene.particles){const drift=Math.sin(t*.18+p.phase)*.35;draw(meshes.particle,modelMatrix(p.x+drift,p.y+Math.sin(t*.23+p.phase)*.2,p.z,p.size*8,p.size*8,p.size*8,p.phase),[.55,.8,.82],.18,t,p.phase,0,0);}
    const half=scene.world.width*.5;for(const f of scene.fish){f.x+=f.speed*f.direction*dt*(f.school!=null?1.25:1);if(f.x>half+2)f.x=-half-2;if(f.x<-half-2)f.x=half+2;const z=f.z+Math.sin(t*.22+f.phase)*(f.school!=null?1.4:.55),y=f.y+Math.sin(t*.35+f.phase)*(f.large ? .35 : .18),scale=f.scale*(selected===f?1.08:1);draw(meshes.fish,modelMatrix(f.x,y,z,scale,scale,scale,f.direction<0?Math.PI:0),hsl(f.hue,.55,f.large ? .58 : .5),f.school!=null ? .82 : .96,t,f.phase,.42+f.speed*.25,0);}
    raf=requestAnimationFrame(frame);
  }
  const onLost=(e)=>{e.preventDefault();lost=true;cancelAnimationFrame(raf);showFallback(viewport,'3D描画が一時停止しました。ページを再読み込みすると再開できます。鑑賞記録は失われません。');};canvas.addEventListener('webglcontextlost',onLost,false);raf=requestAnimationFrame(frame);
  return {fallback:false,version:VERSION,scene,camera,reset:()=>camera.reset(),destroy(){lost=true;cancelAnimationFrame(raf);camera.destroy();canvas.removeEventListener('webglcontextlost',onLost);}};
}
root.CinemapOceanWebGL={VERSION,mount};
})(typeof window!=='undefined'?window:globalThis);
