(function(root){'use strict';
function records(){return root.CinemapRecords?.read?.()||{}}
function values(){return Object.values(records()).filter(r=>r&&r.watched)}
function text(id,value){const el=document.getElementById(id);if(el)el.textContent=value}
function renderList(items){const host=document.getElementById('entries');if(!host)return;host.innerHTML=items.length?items.map(r=>'<div class="entry"><div class="name"><strong>'+escapeHtml(r.title||'記録した映画')+'</strong><small>'+(r.year||'')+(r.rating?' · '+Number(r.rating).toFixed(1):'')+'</small></div></div>').join(''):'<p class="empty">まだ記録はありません。</p>'}
function escapeHtml(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function render(){const items=values(),dashboard=document.getElementById('dashboard'),onboarding=document.getElementById('onboarding');if(dashboard)dashboard.hidden=false;if(onboarding)onboarding.hidden=true;text('dashboardCount',items.length+'本記録済み');text('watchedCount',items.length);text('resonatedCount',items.filter(r=>Number.isFinite(Number(r.rating))).length);text('speciesCount',items.length?'· 成長中':'');renderList(items);const species=document.getElementById('speciesCollection');if(species)species.innerHTML=items.length?'<div class="speciesTile"><strong>あなたの海は成長中</strong><small>映画を記録するほど生態系が豊かになります</small></div>':'<p class="empty">映画を記録すると生命が現れます。</p>';const trends=document.getElementById('trends');if(trends)trends.innerHTML=items.length?'<span class="chip">'+items.length+'作品から生成</span>':'<span class="chip">記録待ち</span>';const coverage=document.getElementById('coverage');if(coverage)coverage.textContent=items.length+'作品を記録';const missing=document.getElementById('missing');if(missing)missing.innerHTML='';try{root.CinemapOceanImmersive?.mount?.([],records())}catch(err){console.error('[Ocean dashboard]',err);const e=document.getElementById('loadError');if(e)e.textContent='3D表示に問題がありますが、記録データは引き続き確認できます。'}}
function boot(){try{render();root.CinemapRecords?.subscribe?.(render)}catch(err){console.error('[Ocean boot]',err);const dashboard=document.getElementById('dashboard');if(dashboard)dashboard.hidden=false;const e=document.getElementById('loadError');if(e)e.textContent='海の一部を読み込めませんでした。ページ本文はそのまま利用できます。'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window);
