import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
const errors=[];page.on('pageerror',e=>errors.push('pageerror: '+e.message));page.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});page.on('requestfailed',r=>errors.push('request: '+r.url()+' '+(r.failure()?.errorText||'failed')));
await page.goto('http://127.0.0.1:4174/?preview=100',{waitUntil:'domcontentloaded',timeout:15000});await page.waitForTimeout(900);
const booted=await page.evaluate(()=>!!window.__cinemapOcean);if(!booted)errors.push('Ocean module did not boot');
let world=null;if(booted)try{world=await page.evaluate(async()=>{const w=await Promise.race([window.__cinemapOcean.ready,new Promise((_,reject)=>setTimeout(()=>reject(new Error('asset load timeout')),15000))]);const overflow=window.__cinemapOcean.scene.getObjectByName('cinemap-overflow-school');const instanceColors=overflow?.instanceColor?.array?[...overflow.instanceColor.array]:[];const palette=new Set();for(let i=0;i<instanceColors.length;i+=3)palette.add(instanceColors.slice(i,i+3).map(v=>Math.round(v*20)).join(','));return{logicalCount:w?.logicalCount??-1,primaryCount:w?.primaryCount??-1,overflowCount:w?.overflowCount??-1,overflowInstances:overflow?.count??0,paletteSize:palette.size,preview:window.__cinemapOceanPreview?.watched??0};});}catch(e){errors.push('asset ready: '+e.message)}
await page.waitForTimeout(700);const canvas=page.locator('canvas');if(await canvas.count()!==1)errors.push('Ocean canvas missing');const box=await canvas.boundingBox();if(!box||box.width<380||box.height<800)errors.push('Ocean canvas does not fill iPhone viewport');
if(world){if(world.preview!==100)errors.push(`preview state should be 100, got ${world.preview}`);if(world.logicalCount!==100)errors.push(`100 watched must keep 100 logical creatures, got ${world.logicalCount}`);if(world.primaryCount+world.overflowCount!==100)errors.push(`detailed + lightweight creatures must equal 100, got ${world.primaryCount}+${world.overflowCount}`);if(world.overflowCount>0&&world.overflowInstances!==world.overflowCount)errors.push(`overflow school must render each remaining creature, got ${world.overflowInstances}/${world.overflowCount}`);if(world.overflowCount>0&&world.paletteSize<4)errors.push(`overflow fish need visible color diversity, palette size=${world.paletteSize}`)}
await page.screenshot({path:'ocean-mature-iphone.png',fullPage:false});console.log('Ocean 100-film capture:',JSON.stringify(world));await browser.close();if(errors.length){console.error(errors.join('\n'));process.exit(1)}
