import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';import { clone as skeletonClone } from 'three/addons/utils/SkeletonUtils.js';
import { creatureProfile } from './creature-profiles.js';
const draco=new DRACOLoader();draco.setDecoderPath('./draco/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);const url=(kind,name)=>new URL(`../assets/${kind}/${name}.glb`,import.meta.url).href;
const SPECS={grouper:{kind:'creatures',file:'fish',size:.72,yaw:Math.PI/2,clip:'Fish_Armature|Swimming_Normal'},clown:{kind:'creatures',file:'clownfish',size:.48,yaw:Math.PI},butterfly:{kind:'creatures',file:'butterflyfish',size:.55,yaw:Math.PI},sword:{kind:'creatures',file:'swordfish',size:1.45,yaw:Math.PI},shark:{kind:'creatures',file:'shark',size:2.45,yaw:Math.PI/2,clip:'Fish_Armature|Swimming_Normal'},manta:{kind:'creatures',file:'manta',size:3.15,yaw:Math.PI/2,clip:'Armature|Swim'},whale:{kind:'creatures',file:'whale',size:6.6,yaw:Math.PI/2,clip:'Armature|Swim'},angler:{kind:'creatures',file:'angler',size:.78,yaw:Math.PI/2,clip:'Fish_Armature|Swimming_Normal'},coral:{kind:'habitat',file:'coral',size:7.4,ground:true},rocks:{kind:'habitat',file:'rocks',size:2.8,ground:true},wreck:{kind:'habitat',file:'shipwreck',size:5.2,ground:true}};const cache=new Map();async function source(key){if(cache.has(key))return cache.get(key);const s=SPECS[key],p=loader.loadAsync(url(s.kind,s.file));cache.set(key,p);return p}
function tune(root,key){const habitat=SPECS[key].kind==='habitat';root.traverse(o=>{if(!o.isMesh||!o.material)return;const mats=Array.isArray(o.material)?o.material:[o.material],cloned=mats.map(src=>{const m=src.clone();if('envMapIntensity'in m)m.envMapIntensity=habitat?.16:.32;if('roughness'in m)m.roughness=Math.max(habitat?.78:.5,m.roughness??.6);if('metalness'in m)m.metalness=Math.min(.06,m.metalness??0);if(habitat&&m.color){const neutral=new THREE.Color(0x295249);m.color.lerp(neutral,key==='coral'?.62:.24)}if('emissive'in m&&habitat)m.emissive.multiplyScalar(.08);m.side=THREE.DoubleSide;return m});o.material=cloned.length===1?cloned[0]:cloned})}
async function instance(key,sizeScale=1){const spec=SPECS[key],gltf=await source(key),raw=skeletonClone(gltf.scene);raw.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(raw),dims=box.getSize(new THREE.Vector3()),max=Math.max(dims.x,dims.y,dims.z)||1,center=box.getCenter(new THREE.Vector3()),holder=new THREE.Group();holder.add(raw);raw.position.set(-center.x,spec.ground?-box.min.y:-center.y,-center.z);holder.scale.setScalar(spec.size*sizeScale/max);holder.rotation.y=spec.yaw||0;tune(raw,key);let mixer=null;if(spec.clip&&gltf.animations.length){mixer=new THREE.AnimationMixer(raw);const clip=THREE.AnimationClip.findByName(gltf.animations,spec.clip)||gltf.animations[0];if(clip)mixer.clipAction(clip).play()}return{holder,mixer}}
function seeded(i){const x=Math.sin(i*9283.17)*43758.5453;return x-Math.floor(x)}function circuit(obj,index,{radius=6,y=0,z=-30,speed=.07,phase=Math.PI/2,bob=.5,spread=1,turnRadius=6}={}){return{obj,phase:phase+(index%7-3)*.23,radius:radius*(.86+seeded(index+8)*.25),y:y+(seeded(index+2)-.5)*3.2*spread,z:z+(seeded(index+4)-.5)*7*spread,speed:speed*(.82+seeded(index+6)*.35),bob,turnRadius}}
function stateOf(ecosystem){const stats=ecosystem?.stats||{},habitat=ecosystem?.habitat||{};return{watched:Math.max(0,Number(stats.watched)||0),maturity:Math.max(0,Math.min(1,Number(ecosystem?.maturity)||0)),reef:Math.max(0,Math.min(1,Number(habitat.reef)||0)),vegetation:Math.max(0,Math.min(1,Number(habitat.vegetation)||0)),distantLife:Math.max(0,Math.min(1,Number(habitat.distantLife)||0)),schools:Number(habitat.schools)||0,organisms:Array.isArray(ecosystem?.organisms)?ecosystem.organisms:[]}}
const FAMILY_ASSET={whale:'whale',whaleshark:'shark',hammerhead:'shark',tigershark:'shark',manta:'manta',mantaray:'manta',eagleray:'manta',stingray:'manta',swordfish:'sword',sailfish:'sword',clownfish:'clown',angler:'angler',deep:'angler',grouper:'grouper'};
function assetFor(o,p){if(FAMILY_ASSET[o?.family])return FAMILY_ASSET[o.family];if(p?.silhouette==='shark')return'shark';if(p?.silhouette==='ray')return'manta';if(p?.silhouette==='needle')return'sword';if(o?.niche==='reef')return Number(o?.atlas)%2?'clown':'butterfly';if(o?.niche==='drifter'||o?.niche==='benthic')return'angler';return Number(o?.atlas)%3===0?'butterfly':'grouper'}
function population(state,caps){const max=Math.max(1,caps?.life||32),life=[];if(state.organisms.length){state.organisms.slice(0,24).forEach((o,i)=>{const p=creatureProfile(i),hero=Boolean(o.hero),key=assetFor(o,p),base=Math.max(.42,Math.min(1.65,(Number(o.scale)||1)*p.scale));const school=hero?1:p.grouping==='school'?Math.max(2,Math.min(5,2+Math.floor(state.schools/2))):p.grouping==='loose'?2:1;for(let member=0;member<school&&life.length<max;member++)life.push({key,scale:base*(member?(.62+seeded(i*7+member)*.2):1),hero,niche:o.niche||'pelagic',index:i,member,profile:p});});return life}const count=Math.min(max,Math.max(1,Math.round(2+state.watched*.5+state.schools*2)));return Array.from({length:count},(_,i)=>{const p=creatureProfile(i);return{key:assetFor({},p),scale:.62*p.scale,hero:false,niche:'pelagic',index:i,member:0,profile:p}})}
function habitatPlan(state,caps){const growth=Math.max(state.maturity,state.reef*.9,state.vegetation*.7),max=Math.max(1,Math.min(12,Math.round((caps?.habitat||8)/9))),keys=['rocks','rocks','coral','rocks','coral','rocks','coral','wreck','rocks','coral','rocks','coral'];return keys.slice(0,max).map((key,i)=>({key,scale:key==='wreck'?.5:key==='coral'?.28+state.reef*.24:.38+growth*.22+seeded(i)*.12,index:i}))}
export async function createAssetWorld(scene,ecosystem=null,renderState={}){const root=new THREE.Group();root.name='cinemap-asset-ecosystem';scene.add(root);const mixers=[],movers=[],state=stateOf(ecosystem),caps=renderState.caps||{life:32,habitat:72};if(state.watched===0)return{root,update(){},dispose(){draco.dispose();scene.remove(root)}};
const plan=habitatPlan(state,caps),habitat=await Promise.all(plan.map(s=>instance(s.key,s.scale)));habitat.forEach(({holder},i)=>{const ring=i%2?9:6.5,a=i*2.399;holder.position.set(Math.cos(a)*ring,-7.2,-36-Math.floor(i/2)*5+Math.sin(a)*2.5);holder.rotation.y+=a+.4;root.add(holder)});
const life=population(state,caps),entries=await Promise.all(life.map(o=>instance(o.key,o.scale*(o.hero?1.12:1))));entries.forEach((entry,i)=>{const o=life[i],p=o.profile||creatureProfile(i);root.add(entry.holder);if(entry.mixer)mixers.push(entry.mixer);const reef=o.niche==='reef',deep=o.niche==='benthic'||o.niche==='drifter',hero=o.hero||['whale','shark','manta'].includes(o.key),depthY=p.depthBand==='near'?2.6:p.depthBand==='far'?-1.4:.6,schoolPhase=(o.member||0)*.11;movers.push(circuit(entry.holder,i,{radius:hero?Math.max(8,p.turnRadius):reef?Math.max(3.8,p.turnRadius):Math.max(5,p.turnRadius),y:deep?-3.4:hero?4.5:depthY,z:-28-(o.index%7)*6.2-(o.member||0)*.35,speed:(hero?.022:deep?.03:.05)*p.speed,bob:deep?.2:hero?.55:.28+.15*p.scale,spread:hero?.2:.72,phase:Math.PI/2+p.phase+schoolPhase,turnRadius:p.turnRadius}))});
let elapsed=0;return{root,update(dt){elapsed+=dt;mixers.forEach(m=>m.update(dt));for(const m of movers){const a=elapsed*m.speed+m.phase;m.obj.position.set(Math.cos(a)*m.radius,m.y+Math.sin(a*1.7)*m.bob,m.z+Math.sin(a)*m.radius*.32);m.obj.rotation.y=Math.atan2(-Math.sin(a)*m.radius,Math.cos(a)*m.radius*.32);m.obj.rotation.z=Math.sin(a)*.022}},dispose(){draco.dispose();scene.remove(root)}}}
