import * as THREE from 'three';
import { clampDevicePixelRatio } from './runtime-policy.js';
import { selectQuality, maturityCaps } from './quality.js';
import { ecosystemMaturity } from './creature-profiles.js';
import { createEnvironment } from './environment.js';
import { createAssetWorld } from './asset-world.js';

export function createOceanRenderer(canvas,dpr=globalThis.devicePixelRatio||1){if(!canvas)throw new Error('Ocean renderer requires a canvas');const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(clampDevicePixelRatio(dpr));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.98;return renderer}
function recordCount(ecosystem){const watched=Number(ecosystem?.stats?.watched);if(Number.isFinite(watched))return Math.max(0,watched);return Array.isArray(ecosystem?.organisms)?ecosystem.organisms.length:0}
export function mountOcean(canvas,options={}){
  const reduced=options.reducedMotion===true,quality=selectQuality({width:canvas.clientWidth||390,dpr:globalThis.devicePixelRatio||1,cores:globalThis.navigator?.hardwareConcurrency||4,reducedMotion:reduced}),count=recordCount(options.ecosystem),maturity=ecosystemMaturity(count),caps=maturityCaps(quality,count),renderer=createOceanRenderer(canvas,quality.dpr),scene=new THREE.Scene();scene.background=new THREE.Color(0x073946);
  const camera=new THREE.PerspectiveCamera(48,1,.1,240);const environment=createEnvironment(scene,{...quality,particles:caps.particles,maturity});
  let assetWorld=null,assetError=null;const ready=createAssetWorld(scene,options.ecosystem||null,{quality,caps,maturity}).then(w=>(assetWorld=w,w)).catch(err=>{assetError=err;console.error('[Ocean assets]',err);throw err});
  const clock=new THREE.Clock();let raf=0,disposed=false,yaw=0,pitch=0,targetYaw=0,targetPitch=0,distance=38,targetDistance=38,lastPinch=0;const look=new THREE.Vector3(0,.2,-40),pointers=new Map();
  function resize(){const w=Math.max(1,canvas.clientWidth||390),h=Math.max(1,canvas.clientHeight||520);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
  function pinchDistance(){const pts=[...pointers.values()];if(pts.length<2)return 0;return Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)}
  const down=e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture?.(e.pointerId);if(pointers.size===2)lastPinch=pinchDistance()},move=e=>{const prev=pointers.get(e.pointerId);if(!prev)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){const d=pinchDistance();if(lastPinch)targetDistance=THREE.MathUtils.clamp(targetDistance-(d-lastPinch)*.11,14,96);lastPinch=d;return}const dx=e.clientX-prev.x,dy=e.clientY-prev.y;targetYaw-=dx*.0065;targetPitch=THREE.MathUtils.clamp(targetPitch-dy*.0052,-.36,.26)},up=e=>{pointers.delete(e.pointerId);lastPinch=pointers.size===2?pinchDistance():0},wheel=e=>{e.preventDefault();targetDistance=THREE.MathUtils.clamp(targetDistance+e.deltaY*.03,14,96)};canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',up);canvas.addEventListener('wheel',wheel,{passive:false});
  function frame(){if(disposed)return;resize();const dt=Math.min(.034,clock.getDelta()),t=clock.elapsedTime;yaw=THREE.MathUtils.damp(yaw,targetYaw,4.2,dt);pitch=THREE.MathUtils.damp(pitch,targetPitch,4.2,dt);distance=THREE.MathUtils.damp(distance,targetDistance,4,dt);camera.position.set(Math.sin(yaw)*distance,4.2+pitch*18,look.z+Math.cos(yaw)*distance);camera.lookAt(look.x,look.y+pitch*4.5,look.z);environment.update(t);if(!reduced)assetWorld?.update(dt);renderer.render(scene,camera);raf=requestAnimationFrame(frame)}frame();
  return{renderer,scene,camera,quality,maturity,caps,ready,get assetError(){return assetError},dispose(){disposed=true;cancelAnimationFrame(raf);for(const [n,f] of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['wheel',wheel]])canvas.removeEventListener(n,f);assetWorld?.dispose();renderer.dispose();canvas.width=canvas.width}};
}
