from pathlib import Path
p=Path('search.html')
s=p.read_text(encoding='utf-8')
old='function verdictV3(score){return score>=5?"最優先":score>=4?"かなり向く":score>=3?"候補":score>=2?"優先度低め":"通常上映で十分"}'
new='function formatVerdictLabelV4(x){if(x.key==="standard")return x.score>=5?"通常上映がおすすめ":x.score>=4?"十分楽しめる":"プレミアム方式を優先";if(x.key==="imax"&&x.score===5&&x.optimization===5)return "IMAX一択";return x.score>=5?"最優先で選ぶ":x.score>=4?"有力な選択肢":x.score>=3?"好みが合えば選ぶ":x.score>=2?"追加料金の優先度は低い":"通常上映を優先"}'
if old not in s: raise SystemExit('verdict function anchor not found')
s=s.replace(old,new,1)
old='if(key==="imax"){score=clampScore(optimization*.7+compatibility*.3);if(optimization<=1)score=Math.min(score,2)}else if(key==="dolby_cinema")'
new='if(key==="imax"&&e.filmed_for_imax===true&&e.imax_expanded_ratio&&e.imax_expanded_ratio!=="unknown")score=5;else if(key==="imax"){score=clampScore(optimization*.7+compatibility*.3);if(optimization<=1)score=Math.min(score,2)}else if(key==="dolby_cinema")'
if old not in s: raise SystemExit('score anchor not found')
s=s.replace(old,new,1)
old='function screeningRecommendationV3Html(m){window.__screeningCurrentMovie=m;const rows=scoreScreeningFormatsV3(m),recommended=rows.slice().sort((a,b)=>b.score-a.score||(["standard","imax","dolby_cinema","motion","screenx"].indexOf(a.key)-["standard","imax","dolby_cinema","motion","screenx"].indexOf(b.key)))[0];const heroReason=recommended.key==="standard"?"プレミアム方式の追加価値が弱いため、追加料金をかけず通常上映を優先。":recommended.compatibilityWhy;return \'<div class="section" data-screening-v3-host><h3>どの上映方式で見る？</h3><div class="formatHero"><div class="formatHeroEyebrow">この作品なら</div><div class="formatHeroTitle">\'+E(recommended.name)+\' <span class="formatHeroStars">\'+starText(recommended.score)+\'</span></div><div class="formatHeroReason">\'+E(heroReason)+\'</div></div><div class="formatCompactGrid">\'+rows.map(x=>\'<details class="formatCompact" data-format-detail data-format-key="\'+x.key+\'"><summary><span class="formatCompactName">\'+E(x.name)+\'</span><span class="formatCompactStars">\'+starText(x.score)+\'</span><span class="formatCompactVerdict">\'+E(verdictV3(x.score))+\'</span></summary><div class="formatCompactBody"><div class="formatMetric"><b>作品との相性</b><span>\'+starText(x.compatibility)+\' · \'+E(x.compatibilityWhy)+\'</span></div><div class="formatMetric"><b>専用最適化</b><span>\'+starText(x.optimization)+\' · \'+E(x.optimizationWhy)+\'</span></div><div class="formatMetric"><b>判定根拠</b><span>\'+E(x.key==="dolby_cinema"?"暗部・色彩・撮影美・音楽・空間音響を重視。":x.key==="motion"?"乗り物・高速移動・戦闘・爆発・風・水など身体性を重視。":x.key==="screenx"?"景観・宇宙・海・飛行・群衆・ライブなど空間没入性を重視。":x.key==="imax"?"IMAX撮影・拡張画角を最重視し、スペクタクル適性を補助評価。":"他方式の固有メリットと追加料金を比較。")+\'</span></div>\'+(x.sources.length?\'<div class="formatSources">\'+x.sources.map(src=>\'<a target="_blank" rel="noopener noreferrer" href="\'+E(src.url)+\'">根拠：\'+E(src.label)+\'</a>\').join(\'\')+\'</div>\':\'\')+\'</div></details>\').join(\'\')+\'</div><div class="formatLegend">★は「専用最適化」と「作品との相性」を方式ごとに異なる重みで評価。対応しているだけでは高評価にしません。</div><a class="formatLink" href="experience.html">上映方式を比較する →</a></div>\'}'
new='function screeningRecommendationV3Html(m){window.__screeningCurrentMovie=m;const rows=scoreScreeningFormatsV3(m),recommended=rows.slice().sort((a,b)=>b.score-a.score||(["standard","imax","dolby_cinema","motion","screenx"].indexOf(a.key)-["standard","imax","dolby_cinema","motion","screenx"].indexOf(b.key)))[0],imaxLocked=recommended.key==="imax"&&recommended.score===5&&recommended.optimization===5;const heroReason=imaxLocked?"IMAX撮影と拡張画角を確認済み。通常上映では失われる画面情報があるため、IMAXを最優先。":recommended.key==="standard"?"プレミアム方式の追加価値が弱いため、追加料金をかけず通常上映を優先。":recommended.compatibilityWhy;return \'<div class="section" data-screening-v3-host><h3>どの上映方式で見る？</h3><div class="formatHero"><div class="formatHeroEyebrow">この作品なら</div><div class="formatHeroTitle">\'+E(recommended.name)+(imaxLocked?\' 一択\':\'\')+\' <span class="formatHeroStars">\'+starText(recommended.score)+\'</span></div><div class="formatHeroReason">\'+E(heroReason)+\'</div></div><div class="formatCompactGrid">\'+rows.map(x=>\'<details class="formatCompact" data-format-detail data-format-key="\'+x.key+\'"><summary><span class="formatCompactName">\'+E(x.name)+\'</span><span class="formatCompactStars">\'+starText(x.score)+\'</span><span class="formatCompactVerdict">\'+E(formatVerdictLabelV4(x))+\'</span></summary><div class="formatCompactBody"><div class="formatMetric"><b>この作品で効くポイント</b><span>\'+E(x.compatibilityWhy)+\'</span></div><div class="formatMetric"><b>方式固有の裏付け</b><span>\'+E(x.optimizationWhy)+\'</span></div><div class="formatMetric"><b>なぜこの評価？</b><span>\'+E(x.key==="dolby_cinema"?"暗部・色彩・撮影美・音楽・空間音響を評価。専用マスターがなくても作品特性が強ければ上がる。":x.key==="motion"?"乗り物・高速移動・戦闘・爆発・風・水など、体感演出に変換できる量と重要度を評価。":x.key==="screenx"?"景観・宇宙・海・飛行・群衆・ライブなど、左右への視野拡張が没入感に効くかを評価。":x.key==="imax"?"IMAX撮影と拡張画角を最優先。両方を公式確認できれば5★固定。未確認なら大画面との相性だけで高得点にしない。":"プレミアム方式で失う・得るものと追加料金を比較した基準点。")+\'</span></div>\'+(x.sources.length?\'<div class="formatSources">\'+x.sources.map(src=>\'<a target="_blank" rel="noopener noreferrer" href="\'+E(src.url)+\'">公式根拠：\'+E(src.label)+\'</a>\').join(\'\')+\'</div>\':\'\')+\'</div></details>\').join(\'\')+\'</div><div class="formatLegend">IMAX撮影と拡張画角を確認済みならIMAXを最優先。Dolby Cinema・4DX/MX4D・ScreenXは「専用対応の有無」だけでなく、作品自体の映像・音・身体性・空間性まで分けて評価します。</div><a class="formatLink" href="experience.html">上映方式を比較する →</a></div>\'}'
if old not in s: raise SystemExit('html function anchor not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('applied screening v4')
# workflow trigger 2
