import { chromium } from 'playwright';
import fs from 'node:fs';
const base='http://127.0.0.1:4173';
const candidates=['index.html','discover.html','my-cinemap.html','preview/ocean/ocean-demo.html?view=dashboard','preview/ocean/benchmark-v9.html'];
fs.mkdirSync('artifacts/mobile-smoke',{recursive:true});
const reefUrl='https://commons.wikimedia.org/wiki/Special:Redirect/file/Great_Barrier_Reef_photos_06.jpg?width=1920';
try{const rr=await fetch(reefUrl,{headers:{'user-agent':'Cinemap visual benchmark/0.9'}});if(rr.ok){fs.writeFileSync('artifacts/mobile-smoke/reef-cc0-source.jpg',Buffer.from(await rr.arrayBuffer()))}}catch(e){console.warn('reef staging skipped:',e.message)}
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push('pageerror: '+e.message));
for(const path of candidates){let res=await page.goto(`${base}/${path}`,{waitUntil:'domcontentloaded'});if(!res||res.status()>=400){if(path==='index.html'||path.startsWith('preview/ocean/'))errors.push(`${path}: HTTP ${res?.status()??'no response'}`);continue}const isDemo=path.startsWith('preview/ocean/ocean-demo'),isProbe=path.startsWith('preview/ocean/benchmark-v9');if(isDemo){const mature=Object.fromEntries(Array.from({length:100},(_,i)=>{const id=700000+i;return[String(id),{id,watched:true,rating:i%19===0?5:i%5===0?4.5:3.5,title:`Smoke film ${i+1}`,genres:[],year:1980+(i%45)}]}));await page.evaluate(records=>localStorage.setItem('cinemap-ocean-demo-records-v1',JSON.stringify(records)),mature);res=await page.reload({waitUntil:'domcontentloaded'})}await page.waitForTimeout((isDemo||isProbe)?2600:250);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);if(overflow>2)errors.push(`${path}: page-level horizontal overflow ${overflow}px`);const safeName=path.split('?')[0].replace(/\.html$/,'').replaceAll('/','-');await page.screenshot({path:`artifacts/mobile-smoke/${safeName}.png`,fullPage:true});if(isProbe){const ready=await page.locator('[data-ocean-benchmark="0.9"][data-ready="true"] canvas').count();if(!ready)errors.push(`${path}: Ocean v0.9 benchmark did not render WebGL2`)}if(isDemo){const scene=await page.locator('.oceanV6Scene').count(),canvas=await page.locator('.oceanCinematicViewport canvas').count(),version=await page.locator('[data-ocean-version="0.8.1"]').count(),marker=await page.getByText('OCEAN v0.8.1',{exact:true}).count(),fallback=await page.locator('.oceanCinematicFallback').count();if(!scene||!version||!marker||(!canvas&&!fallback))errors.push(`${path}: Ocean v0.8.1 shell did not render (scene=${scene}, canvas=${canvas}, fallback=${fallback}, version=${version}, marker=${marker})`);if(fallback)errors.push(`${path}: Ocean v0.8.1 renderer fell back instead of rendering WebGL2`);if(canvas){const box=await page.locator('.oceanCinematicViewport').boundingBox();if(box){await page.mouse.move(box.x+box.width*.78,box.y+box.height*.55);await page.mouse.down();await page.mouse.move(box.x+box.width*.18,box.y+box.height*.43,{steps:12});await page.mouse.up();await page.waitForTimeout(650);await page.screenshot({path:'artifacts/mobile-smoke/preview-ocean-explored.png',fullPage:true})}}}}
await browser.close();if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('Mobile smoke checks passed.');
